# ***Experiment 1 — Python Installation and Starting with Python***
                                                                                            -  Anshul Ghildiyal
                                                                                            -  590031643

**Format:** Every question below follows the same rhythm —

1. **The Campus Life Story (Analogy)** (A continuous, real-world metaphor based on the daily life of a college guy, making the concept instantly intuitive before you read a single line of code.)
2. **The code** (clean, working, commented)
3. **Under the hood** (what's really happening — complexity, gotchas, edge cases)
4. **Level up** (I push the original question further, on my own)

## Question 1 — Interactive mode vs Scripting mode

**Task:** Install Python and understand the difference between the two IDLE modes.

### ***Chapter 1: The Late-Night Cram vs. The Syllabus***
You've just moved into your dorm and the semester is starting. You have two ways to get information.

### The Analogy
-  **Interactive mode** is like rapid-fire texting your project partner at 2 AM before a deadline. You send a quick question, they reply instantly, and you move to the next. It’s great for quick tests, but the conversation gets buried and nothing is formally saved for next semester.

- **Scripting mode** s the Professor's official Syllabus. It is written out completely in a document (the `.py` file) before the semester even starts. You execute the entire plan sequentially from week 1 to week 16, and it can be reused for next year's class.



| | Interactive mode | Scripting mode |
|---|---|---|
| Feels like | WhatsApp texting a classmate | Reading the Semester Syllabus |
| Saved? | No | Yes (`.py` file) |
| Best for | Testing a quick math idea | Real assignments, automation, reuse |

In [1]:
import sys
import platform

print("Python is installed.")
print(f"Python version: {sys.version.split()[0]}")
print(f"Python implementation: {platform.python_implementation()}")
print("Running as a script file, not typed line-by-line in IDLE's >>> prompt.")

Python is installed.
Python version: 3.12.10
Python implementation: CPython
Running as a script file, not typed line-by-line in IDLE's >>> prompt.


### Under the hood
This Jupyter Notebook is technically a hybrid. Each cell behaves like one interactive text message (it runs and shows immediate output, just like typing at the >>> prompt), but the notebook file as a whole is saved and reusable like a script.

![alt text](gemini-svg.svg)

### *Level up*
In professional software engineering, we rely on scripting mode for automated pipelines. But before writing the script, we test complex logic in interactive mode (or a Jupyter cell) to ensure the logic holds up before committing it to the final `.py`| file.

## Question 2 — Printing strings in different formats

**Task:** Write Python programs to print strings in a given manner.

### ***Chapter 2: The Campus Notice Board***
You're trying to promote a tech club meeting, so you head to the campus notice board.

### The Analogy
`print()` is you physically pinning a flyer to the board. Whatever is on the flyer gets shown to the campus. Escape sequences like `\n` are invisible instructions you give yourself—like "leave a blank space and start pinning on the next row below." The board doesn't display the word "backslash n"; it just results in a new line.

In [4]:
# 2(a) A massive banner across the top of the board
print("AI & ML Club Meeting Today!")

# 2(b) Two separate pushpins --> two separate lines automatically
print("Pizza")
print("Provided")

# 2(c) The formatting trick: a newline escape sequence inside ONE string
print("Bring your laptop\nSee you at 5 PM")

# 2(d) The Beginner Trap: Backslash before a digit
print("Event date is 12\\05\\2026")

AI & ML Club Meeting Today!
Pizza
Provided
Bring your laptop
See you at 5 PM
Event date is 12\05\2026


### Under the hood

A backslash followed by a number (like `\0`) looks like an escape sequence, but it isn't standard in Python 3 for regular text. Python will usually keep it literally, but it throws warnings in modern IDEs because it thinks you made a typo.

![alt text](2_SVG.svg)

### *Level up*
To properly print something with heavy backslashes (like a MacOS or Windows file directory), professionals use raw strings by prefixing with an `r`.

`r"Macintosh HD\Users\Ray\Projects"` completely ignores escape sequence rules and prints exactly what you typed.

## Question 3 — Declaring and printing a variable

**Task:** Declare a string variable called `x` and assign it the value `Hello`.

### ***Chapter 3: The Dorm Room Mini-Fridge***
Your dorm room is a mess and you need to store your meal prep.

### The Analogy
A variable is just a **Tupperware container**. The assignment `meal = "Chicken & Rice"` is taking the food, dropping it inside the container, and slapping a masking tape label named *meal* on the outside. `print(meal)` simply means opening the container labeled *meal* and showing your roommate what's inside.

In [9]:
# Labelling the Tupperware 'x' and storing the data inside
x = "Hello, Universe!"

#Opening the container to reveal the contents
print(x)

Hello, Universe!


## Question 4 — Different data types with `print()`

**Task:** Take different data types and print values using the `print()` function.

### ***Chapter 4: Packing the Gym Bag***
You're heading to the campus gym after your machine learning lecture. You quickly realize you can't pack your lifting belt the same way you pack your water bottle.

### The Analogy
Data types are the different categories of gear.
- An ***Integer*** is a solid 45lb barbell plate. No fractions, just a whole number.
- A ***Float*** is your current GPA (e.g., 3.84)—it requires precision and decimals.
- A ***String*** is the text written on your student ID card.
- A ***Boolean*** is your gym membership status: True (Active) or False (Expired). 
- A ***List*** is your push-day workout routine, holding multiple exercises in a specific order.


In [10]:
# The Backpack Inventory
integer_value = 45
float_value = 3.14159
string_value = "Hello, Universe!"
boolean_value = True
list_value = [1, 2, 3, 4, 5, "Bench", "Chair", "Table", True]

# Inspecting the type of gears
print(f"Type of integer_value: {type(integer_value)}")
print(f"Type of float_value: {type(float_value)}")  
print(f"Type of string_value: {type(string_value)}")
print(f"Type of boolean_value: {type(boolean_value)}")
print(f"Type of list_value: {type(list_value)}")

Type of integer_value: <class 'int'>
Type of float_value: <class 'float'>
Type of string_value: <class 'str'>
Type of boolean_value: <class 'bool'>
Type of list_value: <class 'list'>


### Under the hood
Unlike statically typed languages (where you have to strictly label the Tupperware `int weight = 45`), Python is dynamically typed. It looks at the item you put in the box and automatically slaps the correct label on it in memory.

### *Level Up -- Peeking inside the box*

The textbook question stops at "print the value and its type." I wanted to know: *how does Python actually store these differently in memory, and does `a = b` copy the box or just make a second label for the same box?* This distinction (identity vs equality, mutable vs immutable) trips up almost every beginner sooner or later, so it's worth seeing directly rather than being told about it.

In [12]:
import sys

def inspect_value(label, value):
    print(f"{label:10s} | type ={type(value).__name__:6s} | id={id(value)} | size={sys.getsizeof(value)}B")

a = 10
b = 10           # small integers are cached in CPython, so a and b likely points to the same object
c = 10.0
d = [1, 2, 3]
e = d            # e is just another reference to the same list as d
f = list(d)      # f is a new list containing the same elements as d

inspect_value("a", a)
inspect_value("b", b)
print("a is b: ", a is b, "(CPython caches small ints -2 to 256 -- same box, two labels)")
inspect_value("c", c)
inspect_value("d", d)
inspect_value("e (=d)", e)
inspect_value("f (copy)", f)
print("d is e:", d is e, "  <- same object, mutating one mutates 'both'")
print("d is f:", d is f, "  <- different objects")
print("d == f:", d == f, " <- but equal VALUES")

d.append(99)
print("\nAfter d.append(99):")
print("d:", d, "| e:", e, " <- e changed too, because it's the SAME list")
print("f:", f, " <- f is untouched, it was a real copy")

a          | type =int    | id=140715568548568 | size=28B
b          | type =int    | id=140715568548568 | size=28B
a is b:  True (CPython caches small ints -2 to 256 -- same box, two labels)
c          | type =float  | id=1946365851632 | size=24B
d          | type =list   | id=1946367637504 | size=88B
e (=d)     | type =list   | id=1946367637504 | size=88B
f (copy)   | type =list   | id=1946367638784 | size=88B
d is e: True   <- same object, mutating one mutates 'both'
d is f: False   <- different objects
d == f: True  <- but equal VALUES

After d.append(99):
d: [1, 2, 3, 99] | e: [1, 2, 3, 99]  <- e changed too, because it's the SAME list
f: [1, 2, 3]  <- f is untouched, it was a real copy


**Why this matters in real code:** this exact gotcha (`e = d` vs `f = list(d)`) is one of the most common sources of bugs professional developers hit — passing a list into a function and being surprised the original changed outside it. Understanding it now, in Experiment 1, saves debugging pain in every experiment after this one.

## Question 5 & 6 — Combining Names & F-Strings

**Task:** Assign your first name, last name, and nickname. Print your full name by adding them, and format them.

### ***Chapter 5: The LinkedIn Profile Builder***
You're trying to land a DevOps internship, so you need to format your name professionally online.

### The Analogy
The `+` operator on strings is like haphazardly gluing words together.

An f-string, however, is like a premium LinkedIn template. The `{}` brackets are polished placeholders in the digital form where you drop specific variables right into the layout.

In [13]:
# Q5: CONCATENATION
a ="Ray"
b ="Smith"
full_name = a + " " + b
print("Standard Name: ", full_name)


# Q6: F-strings
first_name = "Rayleigh"
last_name = "Smith"
nickname = "Ray"

print(f"Developer Profile: {first_name} ({nickname}) {last_name}")

Standard Name:  Ray Smith
Developer Profile: Rayleigh (Ray) Smith


### ***Edge Case Check***

What happens if someone forgets the middle `" "` separator, or one of the names is empty? Worth checking so the pattern doesn't silently misbehave later.

In [14]:
print(repr("Rohit" + "Sharma"))
print(repr("" + " " + "Sharma"))
print(repr(" ".join(["Rohit", "Sharma"])))

'RohitSharma'
' Sharma'
'Rohit Sharma'


## Question 7 — Printing personal/academic details

**Task:** Declare and assign suitable variables, then print the details in the required format.

### ***The University ID Card***
It's time to get your official campus ID printed so you can access the AI labs.

### The Analogy
This program acts as the **Card Printer**. We take all the individual variables we created and arrange them perfectly onto a structured presentation template to generate your student ID.

In [1]:
name = "RAY"
sap_id = "500069944"
dob = "13 October 2003"
address_line1 = "UPES"
address_line2 = "Bidholi Campus"
pincode = "248007"
programme = "Master's in AI & ML"
semester = 1


print("=" * 40)
print(f"🎓 OFFICIAL STUDENT ID: {name}")
print("=" * 40)
print(f"  > SAP ID    : {sap_id}")
print(f"  > D.O.B     : {dob}")
print(f"  > Campus    : {address_line1}, {address_line2}")
print(f"  > Pincode   : {pincode}")
print(f"  > Major     : {programme}")
print(f"  > Semester  : {semester}")
print("=" * 40)

🎓 OFFICIAL STUDENT ID: RAY
  > SAP ID    : 500069944
  > D.O.B     : 13 October 2003
  > Campus    : UPES, Bidholi Campus
  > Pincode   : 248007
  > Major     : Master's in AI & ML
  > Semester  : 1


![alt text](<Screenshot 2026-07-21 094428.png>)

### *Level up*

If this were a production application for the registrar's office, we wouldn't keep these variables floating around loosely. We would group them into a single Python Dictionary or a Class object (like `Student(name, id, major)`). This would allow the system to generate ID cards for an entire classroom of students at once via a simple loop.

# ***Experiment 2 — Use of Input Statement and Operators***
                                                                                            -  Anshul Ghildiyal
                                                                                            -  590031643

## Question 1
*Covers Lab Questions 1,2,3,4,5,6, and 8*

### ***The Engineering Student's Calculator (Math & Geometry)***
Execute foundational arithmetic operations, evaluate algebraic expressions, and compute geometric formulas (Circle Area, Triangle Area, Hypotenuse).

### The Analogy
You and your study group are trying to calculate the absolute shortest path across the rectangular campus quad so you aren't late for `class (Hypotenuse)`. Then, you need to calculate the exact area of the pizzas you are ordering to ensure maximum food per dollar (Area formulas). Python's arithmetic operators are your digital calculator.

In [2]:
import math

x, y = 9, 7
print(f"Basic Math: Add={x+y}, Sub={x-y}, Mult={x*y}, Div={x/y:.2f}") #

# Computing (x + y) * (x + y) with x=4, y=3
x_test, y_test = 4, 3 
expected_output = 49
actual_output = (x_test + y_test) * (x_test + y_test) #
print(f"Algebra: Expected {expected_output}, Got {actual_output}") #

# --- Q2: Area of a Pizza (Circle) ---
radius = 5.5 
circle_area = math.pi * (radius ** 2) 
print(f"Pizza Area: {circle_area:.2f} sq units")

# --- Q6: Shortest path across the Quad (Hypotenuse) ---
a, b = 3, 4
hypotenuse = math.sqrt(a**2 + b**2)
print(f"Quad Shortest Path (Hypotenuse): {hypotenuse}")

# --- Q8: Area of Campus Lawn (Triangle via Heron's Formula) ---
side_a, side_b, side_c = 3, 4, 5
s = (side_a + side_b + side_c) / 2 # Semi-perimeter
triangle_area = math.sqrt(s * (s - side_a) * (s - side_b) * (s - side_c)) #[cite: 2]
print(f"Lawn Area (Heron's): {triangle_area}")

Basic Math: Add=16, Sub=2, Mult=63, Div=1.29
Algebra: Expected 49, Got 49
Pizza Area: 95.03 sq units
Quad Shortest Path (Hypotenuse): 5.0
Lawn Area (Heron's): 6.0


### Under the hood:

- **Complexity:** 0(1) time and memory. Simple floating-point math.
- **Gotchas**: The divisor operator `/` *always* returns a float in Python 3, even if the result is a clean whole number(e.g. 8/2 = 4.0)
- **Equations** Heron's formula requires the semi-perimeter s.


                - s = (a + b + c)/2
                - Area = ✓s(s-a)(s-b)(s-c)

![alt text](gemini-svg_21.svg)

### *Level up*

We used `.pow()` and `**` for exponents. The `**` operator is evaluated natively at the C-level in Python, making it slightly faster than calling the `math.pow()` function overhead for simple squares.

### ***Edge-Case Tests***

What happens if the sides given for Heron's formula (e.g., 1, 1, 10) don't form a valid triangle? The term inside the square root becomes negative, and `math.sqrt()` will crash with a `ValueError: math domain error.`

## Question 2
*Covers Lab Questions 7,9, and 11*


### ***The Broke College Student (Time & Finance)***
Calculate Simple Interest for a loan, compute the sum of the first $n$ natural numbers, and convert raw seconds into standard hours/minutes/seconds format.

### The Analogy
You just took out a student loan to buy a Macbook Air (Simple Interest). Now you are pulling an all-nighter, staring at a timer showing exactly 7,384 seconds until your 8 AM exam. You use modulo math (the remainder operator) to figure out exactly how many hours and minutes of suffering you have left.

In [1]:
# --- Q7: Student Loan (Simple Interest) ---
principal = 10000 
rate = 8          
time = 2          
simple_interest = (principal * rate * time) / 100 
print(f"Loan Interest Owed: ${simple_interest:.2f}") 

# --- Q11: Sum of first 'n' natural numbers ---
n = 10
# Using the mathematical formula instead of a slow loop: n(n+1)/2
sum_n = n * (n + 1) // 2
print(f"Sum of first {n} numbers: {sum_n}")

# --- Q9: The Exam Countdown (Time Conversion) ---
total_seconds = 7384

# Floor division (//) gets the solid hours. 
hours = total_seconds // 3600

# Modulo (%) gets what's left over AFTER extracting hours, then we divide by 60 for minutes
minutes = (total_seconds % 3600) // 60

# Modulo (%) gets the absolute final leftover seconds
seconds = total_seconds % 60

print(f"Time until exam: {hours} hour(s), {minutes} minute(s), {seconds} second(s)")

Loan Interest Owed: $1600.00
Sum of first 10 numbers: 55
Time until exam: 2 hour(s), 3 minute(s), 4 second(s)


### Under the Hood:
- **Complexity:** O(10) calculations.
- **Gotcha:** Using regular division `/` for time conversion results in messy floats like `2.051` hours. YOu must use floor division `//` to get whole integers. 
- **The Magic of Modulo**: The modulo operator `%` is the VIP of time conversion. `7384 % 3600` essentially asks Python: "If I divide this by 3600 as many times as possible, what is the exact remainder left over?"

![alt text](<gemini-svg (_22.svg>)

### *Level Up*
Professional Python developers bypass writing `//` and `% `separately for time. They use the built-in `divmod()` function, which computes both simultaneously and returns a tuple: `minutes, seconds = divmod(remaining_seconds, 60)`.

### ***Edge-Case Tests***
What if the inputs are negative? Modulo behaves differently with negative numbers in Python compared to C or Java. `-5 % 3` is `1` in Python, but `-2` in C. Always ensure time variables are checked to be $> 0$.

## Question 3
*Covers Lab Questions 10,14, and 15*


### ***Schedule Changes (Swapping & Membership)***
Swap the values of two variables without using a third temporary variable. Use the membership operator to check if an item exists within a sequence or a string

### The Analogy
- **Swapping:** Imagine you have a morning class (Variable A) and an evening class (Variable B). You want to trade them. Normally, you'd need a third "temporary" placeholder slot to hold one while you move the other. But using pure math (or Python magic), you can juggle them directly.
- **Membership:** You are checking a massive, crowded waitlist pinned to a door (a Tuple/Sequence) to see if your exact Student ID number is on it (`in`).

In [2]:
# --- Q10: The Mathematical Swap (No temp variable) ---
a = 25 # Morning Class
b = 40 # Evening Class
print(f"Before math swap: a={a}, b={b}")

a = a + b # a is now 65
b = a - b # b is now 65 - 40 = 25 (Swapped!)
a = a - b # a is now 65 - 25 = 40 (Swapped!)
print(f"After math swap:  a={a}, b={b}") 

# --- The "Pythonic" Swap (Level Up) ---
# Under the hood, this uses Tuple Packing/Unpacking, bypassing math entirely.
a, b = b, a 
print(f"After Python swap: a={a}, b={b} (Back to normal)")

# --- Q14 & 15: The Waitlist Checker (Membership Operator) ---
waitlist_sequence = (10, 20, 56, 78, 89) 
student_number = 56                      
course_name = "Python Programming"       
search_char = "g"                        

# The 'in' keyword returns a Boolean (True/False)
is_enrolled = student_number in waitlist_sequence 
char_found = search_char in course_name          

print(f"Is student {student_number} on the waitlist? {is_enrolled}") 
print(f"Is '{search_char}' in '{course_name}'? {char_found}")        

Before math swap: a=25, b=40
After math swap:  a=40, b=25
After Python swap: a=25, b=40 (Back to normal)
Is student 56 on the waitlist? True
Is 'g' in 'Python Programming'? True


### Under the hood:

- **Gotchas:** The mathematical swap (`a = a + b`) is a classic trick, but in languages like C or Java, it's dangerous. If $a$ and $b$ are huge, $a + b$ causes an Integer Overflow and crashes the system. Python handles arbitrarily large integers, so it's safe here.
- **Complexity:** Searching a tuple with `in` is $O(N)$ time complexity, as it has to scan each item one by one until it finds a match.

![alt text](gemini-svg_23-1.svg)

### ***Edge-Case Test:*** 
Membership checks on strings are case-sensitive! Checking `"p" in "Python"` returns `False`. Always normalize strings using .lower() before checking membership in real applications.

## Question 4
*Covers Lab Questions 12 and 13*


### ***The Late-Night CS Lab (Bitwise Operations)***
Generate a truth table for bitwise operators AND (&), OR (|), XOR (^), and demonstrate bitwise Left Shift and Right Shift

### The Analogy
You are sneaking into the campus server room. Bitwise operators don't do regular math. They are physical switches. They bypass the high-level numbers completely and violently flip the raw 1s and 0s (electricity on/off) inside the computer's memory.
- `A Left Shift (<<)` pushes all the electrical currents to the left, which is a lightning-fast way to multiply by 2.

In [3]:
# --- Q12: Server Room Switches (Truth Table) ---
print("Truth Table for Bitwise Operators:")
print("a b | a&b (AND) | a|b (OR) | a^b (XOR)")
for a in (0, 1):
    for b in (0, 1):
        # & = Both must be 1.  | = Either is 1.  ^ = Must be DIFFERENT.
        print(f"{a} {b} |    {a & b}      |    {a | b}     |    {a ^ b}")

# --- Q13: Bit Shifting (Fast Math) ---
num = 10   # In binary: 1010
shift = 2

# Shifting left by 1 multiplies by 2. Shifting by 2 multiplies by 4 (10 * 4 = 40)
left_shift = num << shift 

# Shifting right by 1 floor-divides by 2. Shifting by 2 divides by 4 (10 // 4 = 2)
right_shift = num >> shift

print("\nBitwise Shifts:")
print(f"Original Num : {num:08b} (Base 10: {num})")
print(f"Left shift 2 : {left_shift:08b} (Base 10: {left_shift})")
print(f"Right shift 2: {right_shift:08b} (Base 10: {right_shift})")

Truth Table for Bitwise Operators:
a b | a&b (AND) | a|b (OR) | a^b (XOR)
0 0 |    0      |    0     |    0
0 1 |    0      |    1     |    1
1 0 |    0      |    1     |    1
1 1 |    1      |    1     |    0

Bitwise Shifts:
Original Num : 00001010 (Base 10: 10)
Left shift 2 : 00101000 (Base 10: 40)
Right shift 2: 00000010 (Base 10: 2)


### Under the hood:
- **Complexity:** $O(1)$. This is the absolute fastest operation a CPU can perform because there is no abstraction layer.
- **Gotchas:** Do not confuse bitwise `&` / `|` with logical `and` / `or`.
    - `True and False` evaluates Boolean logic.
    - `5 & 3` looks at the binary `0101 & 0011` and outputs `0001` (which is the integer 1).

![alt text](gemini-svg_24.svg)

### *Level-Up*
Notice in the code I used the f-string formatting trick `{num:08b}`. This forces Python to display the variable as a raw 8-bit binary string so you can literally see the 1s and 0s shifting left and right in your terminal output.

### ***Edge-Case Tests***
What happens if you try to bit-shift a float? e.g., `3.14 << 1`. Python throws a `TypeError`. Bitwise operations operate strictly on memory integers.

# ***Experiment 3 — Conditional Statements***
                                                                                            -  Anshul Ghildiyal
                                                                                            -  590031643

## Question 1: Divisible by both 3 and 5

**Task:** Check whether a given number is divisible by both 3 and 5.


### ***The Vending Machine Hack***

### The Analogy
You are in the engineering building lobby trying to get a coffee from an ancient, glitchy vending machine. The machine only accepts your digital student payment if you buy items in bulk that satisfy two rules simultaneously: the total price must be evenly divisible by 3 (for the coffee tax) AND by 5 (the standard campus fee). If your cart doesn't satisfy both conditions at the exact same time, the machine rejects your card.

- `and` acts as a strict dual-authentication checkpoint. Both rules must return True to proceed.

In [2]:
num = 45 

# The 'and' operator ensures BOTH conditions are met
if num % 3 == 0 and num % 5 == 0: 
    print(f"{num} is divisible by both 3 and 5") 
else: #
    print(f"{num} is not divisible by both 3 and 5") 

45 is divisible by both 3 and 5


### Under the hood
- **Complexity:** $O(1)$ time complexity.
- **Gotchas:** Python uses short-circuit evaluation. When checking `A and B`, if Python evaluates `A` and finds it is `False`, it immediately stops and rejects the whole statement without ever checking `B`. This saves CPU cycles.

### ***Level up***
Instead of checking divisibility by 3 and 5 separately, a mathematically superior way is to check divisibility by their lowest common multiple (LCM). Since $3 \times 5 = 15$, checking `num % 15 == 0` is faster and does the exact same thing with less code.

![alt text](gemini-svg_31.svg)

## Question 2: Multiple of 5

**Task:** Check whether a given number is a multiple of 5


### ***The Barbell Math***

### The Analogy
After classes, you hit the campus gym for a weightlifting session. You are loading plates onto a barbell. Standard plates jump in increments of 5 (5 lbs, 10 lbs, 25 lbs, 45 lbs). If you try to calculate a total weight and the number doesn't divide perfectly by 5 with zero remainder, you know you've messed up the math or someone snuck a weird micro-plate onto your bar.

In [3]:
num = 37 

# Checking if the remainder is exactly zero
if num % 5 == 0:
    print(f"{num} is a multiple of 5")
else:
    print(f"{num} is not a multiple of 5")

37 is not a multiple of 5


### Under the hood
- **Complexity:** $O(1)$.
- **Gotchas:** A common beginner mistake is using the division operator `/` instead of modulo `%`. `37 / 5` returns `7.4`, which doesn't trigger a clean boolean check. Modulo directly asks, "Is there anything left over?"

### ***Level up***
For simple binary choices like this, professional developers use Ternary Operators (conditional expressions) to condense the logic into a single, highly readable line:
`result = "Multiple of 5" if num % 5 == 0 else "Not a multiple"`

![alt text](gemini-svg_32.svg)

## Question 3: Greatest among two numbers

**Task:** Find the greatest among two numbers. If equal, print `numbers are equal`.


### ***The Hardware Upgrade***

### The Analogy
You are preparing for your Master's program and want to buy a new macOS laptop. You are comparing two different systems at the campus tech store strictly based on their unified memory size. You check Laptop A, then Laptop B. If A is bigger, you take A. If B is bigger, you take B. If they are exactly the same, it's a tie.

- The `if-elif-else` chain ensures you only make one final decision.

In [4]:
a = 15
b = 15

# The control flow strictly evaluates top-to-bottom
if a > b:
    print("Greatest number is", a)
elif b > a:
    print("Greatest number is", b)
else:
    print("numbers are equal")

numbers are equal


In [5]:
a = 15
b = 35

# The control flow strictly evaluates top-to-bottom
if a > b:
    print("Greatest number is", a)
elif b > a:
    print("Greatest number is", b)
else:
    print("numbers are equal")

Greatest number is 35


In [6]:
a = 75
b = 55

# The control flow strictly evaluates top-to-bottom
if a > b:
    print("Greatest number is", a)
elif b > a:
    print("Greatest number is", b)
else:
    print("numbers are equal")

Greatest number is 75


###  Under the hood
- **Complexity:** $O(1)$.
- **Gotchas:** If you use two separate `if` statements instead of `elif`, the Python interpreter has to waste time evaluating the second statement even if the first one was already true. `elif` binds them into a single, mutually exclusive block.

### ***Level Up***
While `if-elif` is great for logic branches, if you only need the mathematical maximum, Python has a built-in C-optimized function: `maximum = max(a, b)`. It is much faster and cleaner for pure data processing.

![alt text](gemini-svg_33-1.svg)

## Question 4: Greatest among three numbers

**Task:** Find the greatest among three numbers (assuming all values are different).

### ***The Algorithm Showdown***

### The Analogy
For your "Modular Algorithmic Trading System" assignment, you've written three different automated trading models. You run them overnight on historical stock market data. In the morning, you need to crown the champion based on their ROI (Return on Investment). You must compare Model A against B and C to declare it the absolute winner.

In [ ]:
a, b, c = 12, 45, 32

# A must beat BOTH opponents to win
if a > b and a > c:
    print("Greatest number is", a)
# B must beat BOTH opponents to win
elif b > a and b > c:
    print("Greatest number is", b)
# If A and B both failed, C is the default winner
else:
    print("Greatest number is", c)

 ### Under the hood
 - **Complexity:** $O(1)$.
 - **Gotchas:** The `else` block at the end is a brilliant fallback. By the time the code reaches else, you have mathematically eliminated `a` and `b`. There is no need to write `elif c > a and c > b:` because it is the only logical conclusion left.

### ***Level up***
If you had 100 trading models instead of 3, writing `if-elif` would be a nightmare. You would place them in a List and use Python's built-in sorting algorithm:
`models = [12, 45, 32]`
`print(sorted(models)[-1])` # Sorts lowest to highest, [-1] grabs the last (biggest) item.

![alt text](gemini-svg_34.svg)

## Question 5: Quadratic equation roots

**Task:** Check whether a quadratic equation has real or imaginary roots and display the roots.

### ***The Physics Lab Simulator***

### The Analogy
You are building a trajectory simulator for a physics class. The quadratic equation tracks the arc of a thrown object. The Discriminant ($b^2 - 4ac$) acts as the reality check. If it's positive, the object hit the ground in reality (Real Roots). If it's negative, the math breaks reality, meaning the object never crossed the ground axis (Imaginary Roots).

In [7]:
import cmath 

# Equation format: ax^2 + bx + c = 0
a, b, c = 1, 2, 5

discriminant = b ** 2 - 4 * a * c

# cmath is used here because math.sqrt crashes on negative numbers
root1 = (-b + cmath.sqrt(discriminant)) / (2 * a)
root2 = (-b - cmath.sqrt(discriminant)) / (2 * a)

if discriminant >= 0:
    print("Roots are real")
else:
    print("Roots are imaginary")

print(f"Root 1: {root1}")
print(f"Root 2: {root2}")

Roots are imaginary
Root 1: (-1+2j)
Root 2: (-1-2j)


### Under the hood
- **Complexity:** $O(1)$.
- **Gotchas:** Standard `math.sqrt(-4)` will throw a `ValueError` because you can't square root a negative number in basic arithmetic. Python provides the `cmath` (Complex Math) module specifically to handle imaginary numbers gracefully without crashing the pipeline.

### ***Level up***
In Python, imaginary numbers are represented with a `j` suffix rather than the mathematical `i` (e.g., `1+2j`). You can isolate the real and imaginary parts programmatically using `root1.real` and `root1.imag`.

In [9]:
# Access the real and imaginary components separately

print("The roots we found were: ")

print(f"Root 1: {root1}")
print(f"Root 2: {root2}")

print("\nBreaking the complex numbers into parts:")

print(f"Root 1 -> Real: {root1.real}, Imaginary: {root1.imag}")
print(f"Root 2 -> Real: {root2.real}, Imaginary: {root2.imag}")

The roots we found were: 
Root 1: (-1+2j)
Root 2: (-1-2j)

Breaking the complex numbers into parts:
Root 1 -> Real: -1.0, Imaginary: 2.0
Root 2 -> Real: -1.0, Imaginary: -2.0


![alt text](gemini-svg_35.svg)

## Question 6: Leap Year

**Task:** Find whether a given year is a leap year or not.

### ***The Calendar Edge Case***

### The Analogy
You are coding an automated study planner. February usually has 28 days, but leap years mess up the schedule. The rule isn't just "every 4 years." It's actually a nested logic trap: It is a leap year every 4 years, unless it's a new century (like 1900), then it's not—unless it's a century divisible by 400 (like 2000), then it is. It's the ultimate conditional obstacle course.

In [ ]:
year = 2024

# The logical obstacle course
if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
    print(year, "is a leap year")
else:
    print(year, "is not a leap year"ar = 4056)

2024 is a leap year


In [14]:
year2 = 4058

if (year2 % 400 == 0) or (year2 % 4 == 0 and year2 % 100 != 0):
    print(year2, "is a leap year")
else:
    print(year2, "is not a leap year")

4058 is not a leap year


### Why does Python check `% 400` for a leap year?

At first glance, this condition looks confusing:

```python
if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
```

A common misconception is:

> "A leap year has **366 days**, so why are we dividing the **year** by **400**?"

The answer is that **Python is not checking the number of days in a year.**

It is checking **the year number itself** according to the rules of the **Gregorian Calendar**.

For example:

```python
year = 2024

print(year % 4)    # 0
print(year % 100)  # 24
print(year % 400)  # 24
```

The `%` (modulo) operator returns the **remainder** after division.

- `2024 % 4 == 0` → 2024 is divisible by 4 ✅
- `2024 % 100 != 0` → 2024 is **not** divisible by 100 ✅
- Therefore, **2024 is a leap year.**

---

### Why isn't every year divisible by 4 a leap year?

If the leap year rule were simply:

```python
if year % 4 == 0:
    print("Leap year")
```

then years like **1700, 1800, 1900, and 2100** would incorrectly become leap years.

The problem is that the Earth **doesn't orbit the Sun in exactly 365.25 days.**

It actually takes approximately:

```text
365.2422 days
```

Adding one extra day every four years introduces a small error that accumulates over centuries.

To correct this drift, the **Gregorian Calendar** adds two additional rules.

---

### The Gregorian Calendar Rules

***Rule 1***

Every year divisible by **4** is a leap year.

Examples:

- ✅ 2016
- ✅ 2020
- ✅ 2024

---

***Rule 2***

However, years divisible by **100** are **not** leap years.

Examples:

- ❌ 1700
- ❌ 1800
- ❌ 1900
- ❌ 2100

This removes the extra leap days that would slowly shift the calendar.

---

***Rule 3***

There's one final exception.

Years divisible by **400** **are** leap years.

Examples:

- ✅ 1600
- ✅ 2000
- ✅ 2400

This rule compensates for skipping too many leap years and keeps our calendar aligned with Earth's orbit.

---

***Examples***

| Year | Divisible by 4 | Divisible by 100 | Divisible by 400 | Leap Year? |
|------:|:--------------:|:----------------:|:----------------:|:----------:|
| 2024 | ✅ | ❌ | ❌ | ✅ |
| 1900 | ✅ | ✅ | ❌ | ❌ |
| 2000 | ✅ | ✅ | ✅ | ✅ |
| 2100 | ✅ | ✅ | ❌ | ❌ |

---

***Breaking down the Python condition***

```python
if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
```

Let's read it like English:

```
IF the year is divisible by 400

        OR

IF the year is divisible by 4
AND
it is NOT divisible by 100

THEN
    It is a leap year.
```

This is simply a compact implementation of the Gregorian Calendar rules.

---

***A beginner-friendly version***

The exact same logic can be written in a way that's easier to read:

```python
year = 2024

if year % 400 == 0:
    print("Leap year")

elif year % 100 == 0:
    print("Not a leap year")

elif year % 4 == 0:
    print("Leap year")

else:
    print("Not a leap year")
```

Many beginners find this version easier because it follows the calendar rules step by step instead of combining them into one long Boolean expression.

---

### ***Key Takeaway***

The modulo operator (`%`) is **checking the year number**, **not** the number of days in that year.

The numbers **4**, **100**, and **400** are historical rules from the **Gregorian Calendar**, designed to keep our calendar synchronized with Earth's actual orbital period of approximately **365.2422 days**.

### Under the hood
- **Complexity:** $O(1)$.
- **Gotchas:** Operator precedence is critical here. The parentheses `()` ensure the `and` condition is evaluated strictly together as one unit before the `or` condition is considered. Without them, the logic can leak.

### ***Level up***
While it's great to know the math, professional engineers don't rewrite calendar logic from scratch because it's prone to bugs. Python has a standard library for this:

- `import calendar`
- `is_leap = calendar.isleap(2024)`

In [15]:
import calendar

years = [1900, 2000, 2024, 2025, 2100]

for year in years:
    if calendar.isleap(year):
        print(f"{year}: Leap Year")
    else:
        print(f"{year}: Not a Leap Year")

1900: Not a Leap Year
2000: Leap Year
2024: Leap Year
2025: Not a Leap Year
2100: Not a Leap Year


![alt text](gemini-svg_36.svg)

## Question 7: Next date in calendar

**Task:** Take any date as input and display the next date in the calendar.

### ***The Deadline Calculator***

### The Analogy
Your professor assigns a project and says, "It's due tomorrow." If today is September 20th, it's easy—it's due the 21st. But what if today is December 31st? You can't just add `+ 1` to the day, or you'll get December 32nd. You need a system that understands how months and years roll over automatically.

In [16]:
from datetime import date, timedelta

d = date(2005, 9, 20)

# timedelta acts as a safe math operator for time, handling rollovers
next_day = d + timedelta(days=1)

# .strftime() formats the raw datetime object into a human-readable string
print("Input date:", d.strftime("%d-%m-%Y"))
print("Next date:", next_day.strftime("%d-%m-%Y"))

Input date: 20-09-2005
Next date: 21-09-2005


### Under the hood
- **Complexity:** $O(1)$.
- **Gotchas:** Attempting to manipulate dates using standard integers (e.g., `day += 1`) will eventually destroy your database when it hits edge cases like Leap Years or month ends. `datetime` objects encode the complex rules of the Gregorian calendar natively.

### ***Level up***
If you are building an app where users type the date (like `"20-09-2005"`), you must parse that string into a `datetime` object first before you can do math on it. You use `datetime.strptime(user_string, "%d-%m-%Y")` (String Parse Time) to convert it.

![alt text](gemini-svg_37.svg)

## Question 8: Grade sheet from 5 subjects

**Task:** Print the grade sheet of a student from marks of five subjects. Calculate Percentage, CGPA, and assign a Grade using CGPA ranges.

### ***The Master's Prerequisite***

### The Analogy
It is the end of the semester. You need to hit a specific CGPA threshold in your core AI & ML courses to remain eligible for your Master's enrollment. This program acts as the University Registrar. It ingests your raw scores, aggregates them into a percentage, shrinks that to a 10-point CGPA scale, and then passes it through a strict grading filter to stamp your final transcript.

In [18]:
# The grading filter checks ranges top-to-bottom
def get_grade(cgpa):
    if 0.0 <= cgpa <= 3.4: return "F" 
    if 3.5 <= cgpa <= 5.0: return "C+" 
    if 5.1 <= cgpa <= 6.0: return "B" 
    if 6.1 <= cgpa <= 7.0: return "B+" 
    if 7.1 <= cgpa <= 8.0: return "A" 
    if 8.1 <= cgpa <= 9.0: return "A+"
    if 9.1 <= cgpa <= 10.0: return "O (Outstanding)" 
    return "Invalid CGPA"

# Student Transcript Data
name = "Ray" 
roll_no = "R17234512" 
sap_id = "50005673"
semester = 1 
course = "MCA AI & ML" 

marks = {
    "PDS": 70, 
    "Python": 80, 
    "Chemistry": 90, 
    "English": 60,
    "Physics": 65,
}

# The Aggregation Engine
total = sum(marks.values()) 
percentage = (total / (len(marks) * 100)) * 100 
cgpa = round(percentage / 10, 1) 
grade = get_grade(cgpa) 

# Printing the Official Document
print("--- OFFICIAL GRADESHEET ---")
print(f"Name: {name} | Roll No: {roll_no} | SAPID: {sap_id}") 
print(f"Sem: {semester} | Course: {course}") 
print("-" * 27)
for subject, score in marks.items(): 
    print(f"{subject:<10}: {score}") 
print("-" * 27)
print(f"Percentage: {percentage:.2f}%") 
print(f"CGPA      : {cgpa}") 
print(f"Grade     : {grade}") 

--- OFFICIAL GRADESHEET ---
Name: Ray | Roll No: R17234512 | SAPID: 50005673
Sem: 1 | Course: MCA AI & ML
---------------------------
PDS       : 70
Python    : 80
Chemistry : 90
English   : 60
Physics   : 65
---------------------------
Percentage: 73.00%
CGPA      : 7.3
Grade     : A


### Under the hood
- **Complexity:** $O(N)$ where $N$ is the number of subjects in the dictionary.
- **Gotchas**: Python allows chained comparisons like `8.1 <= cgpa <= 9.0`, which reads beautifully. In languages like C or Java, you would have to break this up into `cgpa >= 8.1 && cgpa <= 9.0`.

### ***Level up***
Instead of hardcoding a massive block of `if` statements, professional architectures store thresholds in a dictionary or data frame. This separates the logic from the data. If the university changes its grading scale, you just update a config file rather than digging into the source code to rewrite `if` conditions.

In [19]:
# Configuration (Can come from JSON/YAML/Database)
grade_scale = [
    {"min": 9.1, "max": 10.0, "grade": "O (Outstanding)"},
    {"min": 8.1, "max": 9.0, "grade": "A+"},
    {"min": 7.1, "max": 8.0, "grade": "A"},
    {"min": 6.1, "max": 7.0, "grade": "B+"},
    {"min": 5.1, "max": 6.0, "grade": "B"},
    {"min": 3.5, "max": 5.0, "grade": "C+"},
    {"min": 0.0, "max": 3.4, "grade": "F"},
]


# Business Logic
def get_grade(cgpa, grading_rules):
    for rule in grading_rules:
        if rule["min"] <= cgpa <= rule["max"]:
            return rule["grade"]
    return "Invalid CGPA"


# Student Transcript
name = "Ray"
roll_no = "R17234512"
sap_id = "50005673"
semester = 1
course = "MCA AI & ML"

marks = {
    "PDS": 70,
    "Python": 80,
    "Chemistry": 90,
    "English": 60,
    "Physics": 65,
}


# Result Calculation
total = sum(marks.values())
percentage = total / len(marks)
cgpa = round(percentage / 10, 1)

grade = get_grade(cgpa, grade_scale)


# Report Card
print("--- OFFICIAL GRADESHEET ---")
print(f"Name: {name} | Roll No: {roll_no} | SAP ID: {sap_id}")
print(f"Semester: {semester} | Course: {course}")
print("-" * 30)

for subject, score in marks.items():
    print(f"{subject:<12}: {score}")

print("-" * 30)
print(f"Percentage : {percentage:.2f}%")
print(f"CGPA       : {cgpa}")
print(f"Grade      : {grade}")

--- OFFICIAL GRADESHEET ---
Name: Ray | Roll No: R17234512 | SAP ID: 50005673
Semester: 1 | Course: MCA AI & ML
------------------------------
PDS         : 70
Python      : 80
Chemistry   : 90
English     : 60
Physics     : 65
------------------------------
Percentage : 73.00%
CGPA       : 7.3
Grade      : A


![alt text](gemini-svg_38.svg)

# ***Experiment 4 — Loops***
                                                                                            -  Anshul Ghildiyal
                                                                                            -  590031643

## Question 1: Factorial using a loop

**Task:** Find factorial of a given number using a loop.

### ***The Progressive Overload Sequence***

### The Analogy
You are planning a brutal ladder routine at the campus gym. Set 1 requires 1 rep, Set 2 requires 1 × 2, Set 3 requires 1 × 2 × 3, and so on. A factorial is the ultimate cumulative grind. You can't skip straight to Set 5; you must loop through and accumulate the volume of every single step before it.

In [20]:
num = 5 
factorial = 1 

# Looping through the sequence to accumulate the multiplier
for i in range(1, num + 1):
    factorial *= i 

print(f"Factorial of {num} is {factorial}")

Factorial of 5 is 120


In [23]:
num = 4
factorial = 2

# Looping through the sequence to accumulate the multiplier
for i in range(1, num + 1):
    factorial *= i 

print(f"Factorial of {num} is {factorial}")

Factorial of 4 is 48


you see changing the value of factorial to `2` gives me `48`... Why is that?

Simply speaking, we were the multiplying all the numbers starting from 1 to n+1 with factorial(which we were supposed to keep 1 as default).
So when we changed the default value to `2`, what we calculated is:

(1 X 2 X 3 X 4) `{values of i}` X 2 `{the factorial we set}` 

resulting in wrong calculation thus giving us 48, rather than 24.

### Under the hood:

- **Gotchas:** The starting value of `factorial` must be `1`. If you initialize it to `0`, the entire multiplication loop will just output `0`. Also, $0!$ mathematically equals $1$, which a simple `range(1, 0)` loop handles correctly by not executing and just returning the initialized `1`.
- **Complexity:** This runs in $O(N)$ time complexity, where $N$ is the target number.

### ***Level up***
For AI & ML data pipelines, writing manual loops for standard math is inefficient. Python has a highly optimized C-based math library. Using `math.factorial(num)` is significantly faster and uses less memory, which is critical when processing large datasets on your machine.

In [24]:
import math

num = 5
# Executed natively in C, bypassing the Python loop overhead entirely
fast_factorial = math.factorial(num)

print(f"Optimized Factorial: {fast_factorial}")

Optimized Factorial: 120


### ***Edge-Case Test:***
Factorials only exist for positive integers and zero. If a user inputs a negative number (e.g., `-5`), the standard loop will just return `1` because `range(1, -4)` is empty. Always add a validation check: `if num < 0: raise ValueError("Factorial does not exist for negative numbers")`.

![alt text](gemini-svg_41.svg)

## Question 2: Armstrong Number

**Task:** Check whether the given number is an Armstrong number.

### ***The Cryptographic Hash Check***

### The Analogy
You are building the security layer for *Modular Algorithmic Trading System* trading API. An Armstrong number is like a perfect cryptographic key: if you shatter the key into individual pieces (digits), power up each piece by the total length of the key, and fuse them back together, it miraculously reconstructs the exact original key. If it's off by even one digit, access is denied.

In [25]:
num = 153
num_str = str(num)
power = len(num_str)
sum_of_powers = 0

# iterating through each elements in the string
for each in num_str:
    sum_of_powers += int(each) ** power

if sum_of_powers == num:
    print(num, "is an Armstrong number")
else:
    print(num, "is not an Armstrong number")

153 is an Armstrong number


In [27]:
num1 = 1678
num_str1 = str(num1)
power1 = len(num_str1)
sum_of_powers1 = 0

for i in num_str1:
    sum_of_powers1 += int(i) ** power1

if sum_of_powers1 == num1:
    print(num1, "is an Armstrong number")
else:
    print(num1, "is not an Armstrong number")

1678 is not an Armstrong number


### Under the hood:

- **Gotchas:** Converting an integer to a string (`str(num)`) is an easy way to iterate over its digits, but string conversion and typecasting back to `int()` inside a loop carries processing overhead.
- **Complexity:** $O(d)$ time complexity, where $d$ is the number of digits in the integer.

### ***Level up***
To optimize this for high-frequency trading pipelines where microseconds matter, we drop the string conversions entirely. We use pure mathematical extraction—Modulo (`% 10`) to grab the last digit, and Floor Division (`// 10`) to chop it off—keeping everything running at the integer level.

In [32]:
# Pure Math Optimization (No String Conversion)
def is_armstrong_optimized(n):
    temp = n
    power = len(str(n)) # Only converting once to get length
    total = 0
    
    while temp > 0:
        digit = temp % 10          # Extracts the last digit
        total += digit ** power
        temp = temp // 10          # Removes the last digit
        
    return total == n

print("Optimized 153 Check:", is_armstrong_optimized(153))

Optimized 153 Check: True


In [31]:
# Pure Math Optimization (No String Conversion)
def is_armstrong_optimized(n):
    temp = n
    power = len(str(n)) # Only converting once to get length
    total = 0
    
    while temp > 0:
        digit = temp % 10          # Extracts the last digit
        total += digit ** power
        temp = temp // 10          # Removes the last digit
        
    return total == n

print("Optimized 1678 Check:", is_armstrong_optimized(1678))

Optimized 1678 Check: False


### ***Edge-Case Test:***
All single-digit numbers (0-9) are technically Armstrong numbers because $X^1 = X$.

![alt text](gemini-svg_42.svg)

## Question 3: Fibonacci series

**Task:** Print Fibonacci series up to a given number of terms.

### ***The Viral Algorithm***

### The Analogy
Imagine the follower growth curve of an ***instagram*** page. At first, it's slow. But soon, the network effect kicks in: the amount of reach you gain today is the sum of the reach from your last two successful posts combined. It cascades and compounds rapidly. That is the Fibonacci sequence in action.

In [33]:
terms = 10
a, b = 0,1

print("Fibonacci series: ")
for _ in range(terms):
    print(a, end =" ")
    #Simultaneous variable swapping using tuple packing
    a, b = b, a + b
print()

Fibonacci series: 
0 1 1 2 3 5 8 13 21 34 


### Under the hood:

- **Gotchas:** The underscore `_` in `for _ in range(terms)` is a Python convention. It tells other developers, "I need to loop exactly this many times, but I don't actually care about using the index variable itself."
- **Complexity:** $O(N)$ time complexity and $O(1)$ space complexity, as we only store the last two variables in memory regardless of how large `N` gets.

### ***Level up***
If you need to generate 100,000 terms for an AI dataset, returning a massive list will cause an out-of-memory error. DevOps architecture uses **Generators** (`yield`). Instead of computing the whole list at once, a generator yields one number, pauses its state in memory, and waits for you to ask for the next one.

In [34]:
# The Generator Approach
def fibonacci_generator(n):
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b

# It only consumes memory for one item at a time
for number in fibonacci_generator(10):
    print(number, end=" ")

0 1 1 2 3 5 8 13 21 34 

### ***Edge-Case Test:***
If `terms` is `0` or negative, the `range(0)` loop simply won't execute, and nothing will print. In a production app, you should return an empty list `[]` or raise an error for invalid constraints.

![alt text](gemini-svg_43.svg)

## Question 4: Prime or not

**Task:** Check whether a given number is prime or not.

### ***The Undivided Schedule***

### The Analogy
A prime number is a completely uninterrupted study day. Your available hours cannot be perfectly divided into smaller blocks by any other event. It's just you and the number 1 (yourself). If an unexpected distraction (a divisor) can perfectly slot into your schedule, the day is no longer prime.

In [35]:
num = 29

if num < 2:
    print(num, "is not prime")
else:
    is_prime = True
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    print(num, "is prime" if is_prime else "is not prime")

29 is prime


In [40]:
num44 = 32

if num44 < 2:
    print(num44, "is not a prime")
else:
    is_prime44 = True

    for j in range(2, int(num44 ** 0.5)+1):
        if num44 % j == 0:
            is_prime44 = False
            break

    print(num44, "is a prime" if is_prime44 else "is not prime")

32 is not prime


### Under the hood:

- **Gotchas:** The `break` statement is crucial. Once you find *one* number that divides perfectly, you know it's not prime. There is zero reason to keep the loop running to check the rest of the numbers.
- **Complexity:** $O(\sqrt{N})$. Checking divisors up to $N$ is slow. By stopping at $\sqrt{N}$ (`int(num ** 0.5)`), a check that would normally take 1,000,000 loops takes exactly 1,000 loops instead.

### ***Level up***
We can optimize this even further. `2` is the only even prime number. We can hardcode a check to eliminate all even numbers instantly, slicing our remaining loop workload strictly to odd numbers.

In [39]:
# Hardware Optimized Prime Check
def is_prime_optimized(n):
    if n in (2, 3): return True
    if n < 2 or n % 2 == 0: return False # Kills 50% of calculations instantly
    
    # Start at 3, and step by 2 (checking only odd numbers)
    for i in range(3, int(n ** 0.5) + 1, 2):
        if n % i == 0:
            return False
    return True

In [41]:
is_prime_optimized(32)

False

In [42]:
is_prime_optimized(29)

True

### ***Edge-Case Test:***
`1` is mathematically not a prime number. The `num < 2` guard clause correctly catches `1`, `0`, and negative numbers, immediately failing them without triggering the loop.

![alt text](gemini-svg_44.svg)

## Question 5: Palindrome Check

**Task:** Check whether a given number is palindrome or not.

### ***The Campus Shuttle Route***

### The Analogy
A palindrome is like taking the campus shuttle. The route from your dorm room to the DevOps lab is the exact same sequence of stops backward as it is forward. No matter which direction you traverse the string, the output data remains perfectly identical.

In [43]:
num = 12321

if str(num) == str(num)[::-1]:
    print(num, "is a palindrome")
else:
    print(num, "is not a palindrome")

12321 is a palindrome


In [44]:
num45 =123421

if str(num45) == str(num)[::-1]:
    print(num45, "is a palindrome")
else:
    print(num45, "is not a palindrome")

123421 is not a palindrome


### Under the hood:

- **Gotchas:** `[::-1]` is Python's slice notation trick to reverse a sequence. It tells the interpreter: "Start from the end, stop at the beginning, and step backward by -1."
- **Complexity:** $O(N)$ where $N$ is the length of the string. String slicing creates a full copy of the string in memory, which is slightly inefficient for massive datasets.

### ***Level up***
If you are asked to solve this in an engineering interview without converting the integer to a string (saving memory), you must reconstruct the number mathematically using our trusty modulo `%` and floor division `//` operators.

In [46]:
# Pure Math Palindrome (No String Allocation)
def is_palindrome_math(n):
    if n < 0: return False
    original, reversed_num = n, 0
    
    while n > 0:
        reversed_num = (reversed_num * 10) + (n % 10) # Push digits left
        n //= 10 # Strip last digit
        
    return original == reversed_num

In [47]:
is_palindrome_math(15478499)

False

In [48]:
is_palindrome_math(45654)

True

In [49]:
is_palindrome_math(456654)

True

### ***Edge-Case Test:***
Numbers ending in zero (e.g., `120`) reversed are `021`. If evaluated as a raw string, they won't match, which is correct. If evaluated as integers, `021` drops the zero to become `21`, which also correctly fails the palindrome test.

## Question 6: Sum of digits

**Task:** Print sum of digits of a number.

### ***The Macro Tracker***

### The Analogy
You are tracking your daily macros for weightlifting. You don't just look at a massive meal and guess; you break the entire plate down into its core components (proteins, fats, carbs) and sum those individual values together to get your final caloric intake.

In [50]:
num46 = 9876
sum_digits = 0

for digit in str(num46):
    sum_digits += int(digit)

print("Sum of digits:", sum_digits)

Sum of digits: 30


### Under the hood:

- **Gotchas:** You cannot loop directly over an integer in Python (e.g., `for digit in 9876:` throws a `TypeError: 'int' object is not iterable`). You must convert it to a string first to make it a sequence.
- **Complexity:** $O(d)$ time complexity where $d$ is the number of digits.

### ***Level up***
This loop is clean, but Python's functional programming tools can execute this in a single, elegant line of code using `map()`. It applies the `int` function to every character in the string simultaneously.

In [51]:
num = 9876
# Map applies int() to every character, sum() adds them up
functional_sum = sum(map(int, str(num)))

print(f"Functional Sum: {functional_sum}")

Functional Sum: 30


### ***Edge-Case Test:***
If the number is negative (e.g., `-9876`), `str(-9876)` contains a `-` character. When the loop attempts to run `int("-")`, the program will violently crash with a `ValueError`. Use `abs(num)` to strip negatives before looping.

![alt text](gemini-svg_45.svg)

## Question 7: Divisible by 5 or 7

**Task:** Count and print all numbers divisible by 5 or 7 between 1 and 100.

### ***The Freelance Payday***

### The Analogy
To fund your new Mac M5, you are doing freelance web dev on the side. Client A pays you every 5 days, and Client B pays you every 7 days. You need to map out every single payday in the 100-day semester so you know when your bank account is getting hit.

In [1]:
numbers = [n for n in range(1, 101) if n % 5 == 0 or n % 7 == 0]
print("Payday Numbers:", numbers)
print("Total Count:", len(numbers))

Payday Numbers: [5, 7, 10, 14, 15, 20, 21, 25, 28, 30, 35, 40, 42, 45, 49, 50, 55, 56, 60, 63, 65, 70, 75, 77, 80, 84, 85, 90, 91, 95, 98, 100]
Total Count: 32


### Under the hood:

- **Gotchas:** The `or` operator natively handles duplicates. If a day is a multiple of *both* 5 and 7 (like day 35), the `or` logic triggers True on the first condition and safely skips the second, preventing day 35 from being incorrectly counted twice.
- **Complexity:** $O(N)$ execution. However, list comprehensions are implemented in C under the hood, making them measurably faster than writing out an indented `for` loop with an `.append()` method.

### ***Level up***
If you are searching through billions of records (big data), allocating a massive list in memory just to count the matches will crash your system. Use a **Generator Expression** bundled with `sum()`. It counts the matches dynamically without ever storing the numbers in memory.

In [2]:
# Generator expression: Uses () instead of []
# Adds 1 to the total for every match found, using virtually 0 RAM
memory_safe_count = sum(1 for n in range(1, 1000000) if n % 5 == 0 or n % 7 == 0)

print(f"Millions of records counted: {memory_safe_count}")

Millions of records counted: 314285


![alt text](gemini-svg_47.svg)

## Question 8: Lowercase to uppercase

**Task:** Convert all lowercase letters to uppercase in a string.

### ***The Loud Roommate***

### The Analogy
Your younger brother is entering the 11th grade, typing out his very first lines of Python code, and he accidentally leaves CAPS LOCK on for his entire script. You need an automated way to transform text formatting without rewriting it manually.

In [3]:
text = "Python Programming Lab"
upper_text = text.upper()

print("Original: ", text)
print("Uppercase: ", upper_text)

Original:  Python Programming Lab
Uppercase:  PYTHON PROGRAMMING LAB


### Under the hood:

- **Gotchas:** Strings in Python are **immutable**. The `.upper()` method does not change the original `text` variable. It creates an entirely new string object in memory and assigns it to `upper_text`.
- **Complexity:** $O(N)$ string traversal.

### ***Level up***
Because this experiment is fundamentally about **Loops**, how does `.upper()` actually work underneath the abstraction? It loops through the ASCII mathematical values of the characters. Lowercase 'a' is 97. Uppercase 'A' is 65. The difference is exactly 32.

In [5]:
# The manual loop showing how the machine processes it
text = "Python Programming Lab"
manual_upper = ""

for char in text:
    # If the character is lowercase (ASCII 97 to 122)
    if 'a' <= char <= 'z':
        # Shift it mathematically by 32 down to the Uppercase ASCII block
        manual_upper += chr(ord(char) - 32)
    else:
        manual_upper += char

print(f"Manual ASCII Loop: {manual_upper}")

Manual ASCII Loop: PYTHON PROGRAMMING LAB


### ***Edge-Case Test:***
Numbers and symbols (like `!`, `@`, `1`) do not have uppercase equivalents in the standard ASCII table. The manual loop specifically guards against corrupting them by checking `if 'a' <= char <= 'z'`.

![alt text](gemini-svg_481-1.svg)

## Question 9: Prime numbers between 1 and 100

**Task:** Print all prime numbers between 1 and 100.

### ***The Study Room Search***

### The Analogy
It is finals week. You are walking through the library corridors (rooms 1 to 100) looking for completely empty study rooms. If even one person (a divisor) is in the room, it’s compromised, and you move on to the next. You need a nested system: walking down the hall (Outer Loop), and looking inside each room (Inner Loop).

In [6]:
primes = []

for num49 in range(2, 101):
    is_prime49 = True

    for i in range(2, int(num49 ** 0.5) + 1):
        if num49 % i == 0:
            is_prime49 = False
            break

    if is_prime49:
        primes.append(num49)

print(f"Prime numbers from 1 to 100 are : {primes}")

Prime numbers from 1 to 100 are : [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


### Under the hood:

- **Gotchas:** The `is_prime` boolean flag must be reset to `True` at the start of *every* iteration of the outer loop. If you place it outside the loops, the moment one number fails, all subsequent numbers will be falsely marked as non-prime.
- **Complexity:** $O(N \sqrt{N})$ because for every $N$ numbers we evaluate, we loop $\sqrt{N}$ times.

### ***Level up***
If you are generating cryptography keys or processing datasets to 1,000,000, this nested loop is too slow. DevOps engineers use an ancient Greek algorithm called the **Sieve of Eratosthenes**. Instead of checking if each room is empty, it walks through and preemptively crosses out all multiples (2s, 3s, 5s), leaving only the primes untouched.

In [7]:
# The Sieve of Eratosthenes (Ultra-fast generation)
def generate_primes(limit):
    sieve = [True] * (limit + 1)
    for p in range(2, int(limit ** 0.5) + 1):
        if sieve[p]:
            # Cross out all multiples of p
            for i in range(p * p, limit + 1, p):
                sieve[i] = False
                
    return [p for p in range(2, limit + 1) if sieve[p]]

print("Fast Primes:", generate_primes(100))

Fast Primes: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


### ***Edge-Case Test:***
Notice both algorithms start the range at `2`. The number `1` is neither prime nor composite. Including it in automated datasets will ruin prime factorization logic down the line.

![alt text](gemini-svg_49.svg)

## Question 10: Multiplication table

**Task:** Print multiplication table for a given number.

### ***The Ladder Progression Scheme***

### The Analogy
You are setting up the workout whiteboard for the gym. You need to map out the weight increments for a 10-set ladder progression of squats. You define your base multiplier, and the loop dynamically calculates and prints exactly what plates need to be loaded on the bar for sets 1 through 10.

In [8]:
num40 = 5

for i in range(1,11):
    print(f"{num40} * {i} = {num40 * i}")

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


### Under the hood:

- **Gotchas:** The `range(start, stop)` function in Python is exclusive at the end. `range(1, 11)` stops at `10`. If you write `range(1, 10)`, your table will end prematurely at 9.
- **Complexity:** $O(N)$ execution. Python 3's `range()` acts as an immutable sequence type, meaning it yields numbers instantly without allocating an entire array in memory.

### ***Level up***
A raw printout works, but for tech dashboards (or a CLI interface), alignment is everything. We can utilize f-string format specifiers (like `:<2`) to ensure double-digit numbers don't push the text out of alignment, creating a perfectly straight visual grid.

In [9]:
num = 5

print("--- DASHBOARD ALIGNED ---")
for i in range(1, 11):
    # :<2 left-aligns the counter to take exactly 2 spaces
    # :<3 left-aligns the result to take exactly 3 spaces
    print(f"|  {num}  x  {i:<2}  =  {num * i:<3} |")
print("-" * 25)

--- DASHBOARD ALIGNED ---
|  5  x  1   =  5   |
|  5  x  2   =  10  |
|  5  x  3   =  15  |
|  5  x  4   =  20  |
|  5  x  5   =  25  |
|  5  x  6   =  30  |
|  5  x  7   =  35  |
|  5  x  8   =  40  |
|  5  x  9   =  45  |
|  5  x  10  =  50  |
-------------------------


### ***Edge-Case Test:***
If you input a zero or a negative number, the math holds up perfectly, but formatting might break if negative signs push the characters out of alignment. Using a dynamic padding variable based on string length is the bulletproof solution for UI development.

![alt text](gemini-svg_40-4.svg)

# ***Experiment 5 — Strings and Sets***
                                                                                            -  Anshul Ghildiyal
                                                                                            -  590031643

## Question 1: Count capital letters

**Task:** Count and display the number of capital letters in a given string.[cite: 5]

### ***The Urgent Email Scanner***

### The Analogy
You are skimming through a messy, panic-typed email from your project partner about a missed deadline. The capital letters are the urgent action items. You need an automated script to scan the document and count exactly how many times they hit the shift key to gauge their panic level.

In [10]:
text = "PyThOn LAB 2026"

# Using a generator expression inside sum() to count True conditions
count_caps = sum(1 for ch in text if ch.isupper())
print("Capital letters:", count_caps)

Capital letters: 6


### Under the hood:

- **Gotchas:** Using a generator expression `(1 for ch in text...)` inside `sum()` is extremely memory efficient. It evaluates the string character by character on the fly, rather than creating a massive secondary list in RAM just to count the items.
- **Complexity:** $O(N)$ where $N$ is the length of the string. Every character must be inspected once.

### ***Level up***
Counting the capital letters is useful, but what if you actually need to read the hidden message they form? We can use `.join()` combined with the same list comprehension to extract and stitch the capital letters together into a new string.

In [11]:
text = "PyThOn LAB 2026"

# Extracting the capitals, not just counting them
hidden_message = "".join(ch for ch in text if ch.isupper())

print(f"Extracted Capitals: {hidden_message}")

Extracted Capitals: PTOLAB


### ***Edge-Case Test:*** 
Numbers, spaces, and symbols (like `2026` or `!`) do not have a case. The `.isupper()` method safely ignores them and returns `False`, ensuring your count isn't corrupted by punctuation.

![alt text](gemini-svg_51.svg)

## Question 2: Count vowels

**Task:** Count total number of vowels in a given string.[cite: 5]

### ***The VIP Guest List***

### The Analogy
You are bouncing at a campus frat party. Hundreds of letters are trying to get in (the string). You hold a specific VIP list (the vowels). As every character walks up, you check if they are on your list. If they are, you click your counter. If they aren't (consonants), you turn them away.

In [12]:
text = "Welcome to Python Programming"
vowels = "aeiouAEIOU"
# Checking if each character holds a spot on the VIP list
count_vowels = sum(1 for ch in text if ch in vowels)
print("Total vowels:", count_vowels) 

Total vowels: 8


### Under the hood:

- **Gotchas:** Checking `ch in "aeiouAEIOU"` means Python does a linear search through the string of vowels every single time. It's fast enough for 10 characters, but at a massive scale, it's structurally inefficient.
- **Complexity:** $O(N \times M)$ where $N$ is the string length and $M$ is the vowel string length (10).

### ***Level up***
For natural language processing (NLP) models where you are scanning entire textbooks, you must use a Python `set` for the VIP list. Sets use C-level Hash Tables, reducing the lookup time from $O(M)$ to $O(1)$ instant verification.

In [13]:
text = "Welcome to Python Programming"
# Defining the VIP list as a Set {} for O(1) hash lookups
vowels_set = {'a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U'}

optimized_count = sum(1 for ch in text if ch in vowels_set)
print(f"Optimized Count: {optimized_count}")

Optimized Count: 8


### ***Edge-Case Test:*** 
Is 'y' a vowel? In English, sometimes. In programming, you must strictly define the parameters. The computer doesn't know grammar rules; it only evaluates exactly what you placed inside the `vowels` variable.

![alt text](gemini-svg_52.svg)

## Question 3: Split sentence into words

**Task:** Input a sentence and print words in separate lines.[cite: 5]

### ***Unpacking the Groceries***

### The Analogy
You just returned from the campus mart with a single, massive plastic bag full of groceries (the sentence). You can't just throw the bag in the fridge. You need to slice the bag open, pull out every distinct item, and place it neatly on its own shelf (separate lines).

In [15]:
sentence = "I should have watched 'The Mentalist' rather than spending my whole day playing basketball."
for word in sentence.split():
    print(word)

I
should
have
watched
'The
Mentalist'
rather
than
spending
my
whole
day
playing
basketball.


### Under the hood:

- **Gotchas:** Calling `.split()` with empty parentheses is magical. It doesn't just split by a single space; it splits by *any* whitespace (tabs, newlines, multiple spaces). If you use `.split(" ")`, a double-space in the text will create an ugly empty string `""` in your list.
- **Complexity:** $O(N)$ where $N$ is the string length. It traverses the string once to build the list of substrings.

### ***Level up***
When scraping web data, words are often stuck to punctuation (e.g., `"learn,"`). A basic `.split()` leaves the comma attached. To clean the groceries as you unpack them, you map a `.strip()` function to shave off the unwanted symbols.

In [18]:
import string

d_sent = "Are you sure about that? Playing basketball is so much better than sitting in a fraking chair all DAYYYY!"

c_words = [word.strip(string.punctuation) for word in d_sent.split()]

for word in c_words:
    print(word)

Are
you
sure
about
that
Playing
basketball
is
so
much
better
than
sitting
in
a
fraking
chair
all
DAYYYY


### ***Edge-Case Test:*** 
If the input string is empty (`""`), `sentence.split()` returns an empty list `[]`, meaning the loop will just gracefully skip execution without throwing an error.

![alt text](gemini-svg_53.svg)

## Question 4: Substring occurrences

**Task:** Enter a string and substring, then print how many times substring occurs from left to right.[cite: 5]

### ***The Plagiarism Checker***

### The Analogy
You are reviewing an essay you wrote at 3 AM. You want to make sure you didn't accidentally overuse the filler word "CDC". The script acts as a plagiarism scanner, reading the document left to right. Once it locks onto the exact sequence, it clicks the counter, steps forward, and continues scanning the rest of the paper.

In [20]:
main_string = "ABCDCDC"
sub_string = "CDC"

count = 0
start = 0

while True:
    # .find() returns the index of the first match, or -1 if not found
    idx = main_string.find(sub_string, start)
    if idx == -1:
        break
    count += 1
    #Shift the starting point forward by 1 to catch overlapping matches
    start = idx + 1

print("Occurence: ", count)

Occurence:  2


### Under the hood:

- **Gotchas:** The logic `start = idx + 1` is brilliant because it catches **overlapping substrings**. In `"ABCDCDC"`, the string `"CDC"` appears twice, overlapping at the middle 'C'. Python's native `main_string.count("CDC")` would return `1` because it skips over the overlap. This manual `.find()` loop catches both!
- **Complexity:** $O(N \times M)$ worst-case time complexity, but Python’s `.find()` uses the highly optimized Boyer-Moore-Horspool algorithm under the C hood.

### ***Level up***
If you are doing advanced string matching (like DNA sequence analysis or complex log parsing), you abandon `.find()` entirely and step up to **Regular Expressions (Regex)**. The `re` module is the industry standard for pattern hunting.

In [21]:
import re

main_string1 = "ABCDCDC"
# Using regex with lookahead (?=...) to find overlapping matches
matches = re.findall(r'(?=CDC)', main_string1)

print(f"Regex Occurrences: {len(matches)}")

Regex Occurrences: 2


### ***Edge-Case Test:*** 
If the `sub_string` is longer than the `main_string`, `.find()` immediately returns `-1` and the loop breaks on iteration 1, safely returning `0` occurrences.

![alt text](gemini-svg_54-2.svg)

## Question 5: Character frequency

**Task:** Count occurrences of each alphabet (case-insensitive) in a mixed-case string.[cite: 5]

### ***The Lecture Notes Tally***

### The Analogy
You've copy-pasted messy lecture notes from three different friends into a massive study guide. Some type in ALL CAPS, some in lowercase. You want to tally the most used concepts, but you need to neutralize the case first so 'Apple' and 'apple' are dropped into the exact same statistical bucket.

In [22]:
text = "ABaBCbGc" 
frequency = {} 

for ch in text: 
    if ch.isalpha(): 
        # Neutralizing the case so 'a' and 'A' hit the same dictionary key
        key = ch.upper() 
        # .get() fetches the current count, defaulting to 0 if not found
        frequency[key] = frequency.get(key, 0) + 1 
# Sorting the dictionary keys alphabetically before printing
for key in sorted(frequency): 
    print(f"{frequency[key]}{key}") 

2A
3B
2C
1G


### Under the hood:

- **Gotchas:** `frequency.get(key, 0)` is a lifesaver. If you try to run `frequency[key] += 1` on a key that doesn't exist yet, Python throws a fatal `KeyError`. The `.get()` method safely initializes the missing key to `0` first.
- **Complexity:** $O(N)$ to parse the string, and $O(K \log K)$ to sort the keys at the end (where $K$ is unique characters).

### ***Level up***
Data scientists don't write manual tally loops. Python provides a high-performance, specialized Dictionary called `Counter` from the `collections` module. It is engineered specifically for frequency mapping.

In [23]:
from collections import Counter

text = "ABaBCbGc"
# Filter to letters, convert to uppercase, and count instantly
optimized_tally = Counter(ch.upper() for ch in text if ch.isalpha())

for key, count in sorted(optimized_tally.items()):
    print(f"{count}{key}")

2A
3B
2C
1G


### ***Edge-Case Test:*** 
What about spaces and numbers? The `.isalpha()` check completely filters out whitespace, commas, and digits, ensuring your final frequency dictionary is strictly alphabetic characters.

![alt text](gemini-svg_55.svg)

## Question 6: Unique words using sets

**Task:** Count number of unique words in a sentence using sets.[cite: 5]

### ***The Club Roster Bouncer***

### The Analogy
You pass a sign-up sheet around the AI & ML club. Some people accidentally write their name twice on the clipboard. A Python `set()` acts as an aggressive bouncer at the door. It completely ignores order and strictly denies duplicates, letting only one instance of every unique attendee into the VIP room.

In [24]:
sentence = "python is simple and python is powerful"

# Lowercase neutralizes case, split() breaks it into a list
words = sentence.lower().split()

# Passing the list through the Set bouncer to destroy duplicates
unique_words = set(words)

print("Unique words:", unique_words)
print("Count of unique words:", len(unique_words))

Unique words: {'python', 'powerful', 'simple', 'is', 'and'}
Count of unique words: 5


### Under the hood:

- **Gotchas:** Sets are **unordered**. When you print `unique_words`, the words will likely not be in the order they appeared in the sentence. If retaining the original sequence is mandatory, you cannot use a basic `set()`.
- **Complexity:** Converting a list to a set is $O(N)$ on average because inserting into a Hash Table is $O(1)$ per word.

### ***Level up***
If you need to remove duplicates but **must keep the original order** of the sentence, you use a trick with `dict.fromkeys()`. Dictionaries in Python 3.7+ guarantee insertion order, and dictionary keys inherently function like a set (no duplicates allowed).

In [26]:
sentence = "python is simple and python is powerful"
# dict keys eliminate duplicates but preserve insertion order!
ordered_unique = list(dict.fromkeys(sentence.lower().split()))

print(f"Ordered Unique: {ordered_unique}")

Ordered Unique: ['python', 'is', 'simple', 'and', 'powerful']


### ***Edge-Case Test:*** 
Punctuation ruins sets. If the sentence was `"python is simple, and python is powerful"`, the set would see `"simple,"` and `"simple"` as two completely different strings. You must strip punctuation before feeding words to a set in production environments.

![alt text](gemini-svg_56.svg)

## Question 7 & 8: Set Operations

**Task:** Create sets and apply mathematical set operations (Union, Intersection, Difference, Symmetric Difference),
### ***The Roommate Fridge Overlap***

### The Analogy
You and your roommate both bought groceries. You each have a shelf (a Set). 
*   **Intersection (`&`):** The things you both bought (Wait, we have two milks?).
*   **Difference (`-`):** Things strictly on *your* shelf, not theirs.
*   **Union (`|`):** The master inventory of the entire fridge (no duplicates).
*   **Symmetric Difference (`^`):** The chaotic items that only one of you bought, excluding the shared staples.

In [ ]:
# Question 7: Fruits
s1 = {"apple", "banana", "mango", "grapes"}
s2 = {"banana", "orange", "kiwi", "mango"}

print("Fruits in both (Intersection):", s1 & s2)
print("Fruits only in s1 (Difference):", s1 - s2) 
print("Count of master inventory:", len(s1 | s2))

print("\n--- Question 8: Colors ---")
S1 = {"Red", "yellow", "orange", "blue"} 
S2 = {"violet", "blue", "purple"}

print("Union (All unique):", S1 | S2) 
print("Intersection (Overlap):", S1 & S2) 
print("Difference S1 - S2:", S1 - S2) 
print("Difference S2 - S1:", S2 - S1) 
print("Symmetric Difference (Non-shared):", S1 ^ S2) 

### Under the hood:

- **Gotchas:** The subtraction order matters immensely! `S1 - S2` removes S2's items from S1. `S2 - S1` is a completely different answer. 
- **Complexity:** Intersection `&` is generally $O(\min(len(s1), len(s2)))$, making it blazingly fast compared to looping through lists to find common items.

### ***Level up***
The mathematical operators (`&`, `|`, `-`) are beautiful, but they strictly require *both* sides to be Sets. If you have a Set of colors and a standard List of colors, `S1 & my_list` will crash. The professional workaround is using the named method `S1.intersection(my_list)`, which automatically accepts and converts any iterable sequence.

In [27]:
S1 = {"Red", "yellow", "orange", "blue"}
list_of_colors = ["blue", "purple", "black"]

# The named method accepts lists, operator '&' does not!
safe_overlap = S1.intersection(list_of_colors)

print(f"Safe Overlap: {safe_overlap}")

Safe Overlap: {'blue'}


### ***Edge-Case Test:*** 
Creating an empty set is a massive beginner trap. If you type `empty = {}`, Python creates an empty **Dictionary**, not a set. To create a blank set for a data pipeline, you MUST type `empty = set()`.

![alt text](gemini-svg_578-1.svg)

# ***Experiment 6 — Lists, Tuples, Dictionary***
                                                                                            -  Anshul Ghildiyal
                                                                                            -  590031643

## Question 1: Count value occurrences

**Task:** Scan `n` values in range `0-3` and print number of times each value has occurred.[cite: 6]

### ***The Meal Plan Tracker***

### The Analogy
You are trying to budget your campus meal plan swipes. The university codes your transactions: `0` for Breakfast, `1` for Lunch, `2` for Dinner, and `3` for Late-Night Snacks. To see where your money is going, you pull the raw array of transaction codes and tally them into specific buckets to see which meal you eat the most.

In [28]:
values = [0, 1, 2, 3, 2, 1, 0, 3, 3, 2]
counts = {0: 0, 1: 0, 2: 0, 3: 0}

for value in values:
    if value in counts:
        counts[value] += 1

for key in counts:
    print(f"Meal Code {key} used {counts[key]} time(s)")

Meal Code 0 used 2 time(s)
Meal Code 1 used 2 time(s)
Meal Code 2 used 3 time(s)
Meal Code 3 used 3 time(s)


### Under the hood:

- **Gotchas:** In a standard dictionary, you cannot increment a key (`counts[value] += 1`) if the key doesn't already exist. The code above safely pre-initializes the keys `0, 1, 2, 3` to `0` to prevent a fatal `KeyError`.[cite: 6]
- **Complexity:** $O(N)$ time complexity. We scan the list of transactions exactly once.

### ***Level up***
Hardcoding the initialization (`{0: 0, 1: 0...}`) is terrible for scalability. If the cafeteria adds a new "Coffee" code (`4`), your program misses it. Professional data pipelines use `collections.Counter` to dynamically tally data without any manual setup.

In [29]:
from collections import Counter

transactions = [0, 1, 2, 3, 2, 1, 0, 3, 3, 2]

# Instantly tallies everything, regardless of what the codes are
dynamic_counts = Counter(transactions)

for code, count in sorted(dynamic_counts.items()):
    print(f"Code {code}: {count}")

Code 0: 2
Code 1: 2
Code 2: 3
Code 3: 3


### ***Edge-Case Test:***
If the API glitches and returns a string `["0", "1"]` instead of integers `[0, 1]`, the manual pre-initialized dictionary will fail to match the keys because `0 != "0"`. The `Counter` level-up handles this flawlessly by dynamically creating string keys.

![alt text](gemini-svg_61.svg)

## Question 2: Tuple average

**Task:** Create a tuple of numeric values and find average.[cite: 6]

### ***The Immutable Transcript***

### The Analogy
A standard Python List `[]` is like a draft of your video script for the *byte&barbell* channel—you can add to it, delete lines, and mutate it continuously. A Tuple `()` is like your finalized University Transcript. Once the registrar locks it in, it becomes **immutable**. You can read the data and average your grades, but you cannot physically alter or append new items to that finalized record.

In [30]:
numbers = (12, 25, 30, 18, 15)
average = sum(numbers) / len(numbers)

print("Finalized Tuple:", numbers)
print("Average Score:", average)

Finalized Tuple: (12, 25, 30, 18, 15)
Average Score: 20.0


### Under the hood:

- **Gotchas:** Because tuples are immutable, they are allocated a fixed block of memory when created. Lists, however, over-allocate memory to leave room for future `.append()` operations.
- **Complexity:** $O(N)$ for the `sum()` function to iterate over the tuple.

### ***Level up***
Why use a Tuple over a List at all if Lists are more flexible? **Performance and Memory.** When feeding massive datasets into an AIML training model where the underlying data should *never* change, wrapping it in a tuple is safer and lighter.

In [31]:
import sys

# Proving the memory difference
mutable_list = [1, 2, 3, 4, 5]
immutable_tuple = (1, 2, 3, 4, 5)

print(f"List Memory : {sys.getsizeof(mutable_list)} bytes")
print(f"Tuple Memory: {sys.getsizeof(immutable_tuple)} bytes (Lighter!)")

List Memory : 104 bytes
Tuple Memory: 80 bytes (Lighter!)


### ***Edge-Case Test:***
If you attempt to run this code on an empty tuple `()`, `len(numbers)` evaluates to `0`, triggering a fatal `ZeroDivisionError`. You should guard this with: `if not numbers: return 0`.

![alt text](gemini-svg_62.svg)

## Question 3: Runner-up score

**Task:** Input scores of students and print runner-up score.[cite: 6]

### ***The Hackathon Leaderboard***

### The Analogy
You are processing the final scores for a campus hackathon. Multiple teams might tie for 1st place with a score of 100. If you just sort the list and grab the second item, you might accidentally grab another team that tied for 1st. You must strip away the duplicates using a Set, sort the pure unique values, and *then* grab the silver medalist.

In [32]:
scores = [2, 3, 6, 6, 5]

# 1. set(scores) removes the duplicate '6'
# 2. sorted(..., reverse=True) orders them highest to lowest [6, 5, 3, 2]
unique_scores = sorted(set(scores), reverse=True)

# 3. [1] grabs the second item in the zero-indexed list
runner_up = unique_scores[1]

print("Runner-up score:", runner_up)

Runner-up score: 5


### Under the hood:

- **Gotchas:** `set(scores)` completely destroys the original order of the list. We *must* use `sorted()` immediately after converting it to a set to re-establish a numerical hierarchy. 
- **Complexity:** $O(N \log N)$ due to Python's internal Timsort algorithm used by `sorted()`.

### ***Level up***
If you are analyzing millions of stock ticks for *Project Vegapunk*, sorting the entire dataset just to find the top two numbers is incredibly wasteful. You can find the runner-up in a single pass $O(N)$ by keeping track of the gold and silver medals dynamically.

In [33]:
scores = [2, 3, 6, 6, 5]
gold = silver = float('-inf')

for score in scores:
    if score > gold:
        silver = gold      # Old gold becomes silver
        gold = score       # New gold is crowned
    elif gold > score > silver:
        silver = score     # New silver crowned, gold untouched

print(f"O(N) Fast Runner-Up: {silver}")

O(N) Fast Runner-Up: 5


### ***Edge-Case Test:***
If every single team in the hackathon got the exact same score (e.g., `[6, 6, 6, 6]`), `set()` shrinks the list to `[6]`. Attempting to access `unique_scores[1]` will crash the program with an `IndexError: list index out of range`.

![alt text](gemini-svg_63.svg)

## Question 4: Dictionary Mapping and Grouping

**Task:** Create a dictionary of persons where key is name and value is city, then display all names, all cities, combinations, and count number of students in each city.[cite: 6]

### ***The Ride-Share Board***

### The Analogy
It's Thanksgiving break. The student union sets up a digital ride-share board. The board maps specific students (Unique Keys) to their hometown destinations (Values). By looping through this dictionary, you can extract a list of all drivers, see everywhere people are traveling, and calculate exactly how many seats are needed for cars heading to specific cities.

In [34]:
students = {
    "Aman": "Dehradun",
    "Riya": "Delhi",
    "Vikas": "Dehradun",
    "Neha": "Mumbai",
}

print("All names:", list(students.keys()))
print("All city names:", list(students.values()))

print("\nStudent and city details:")
# .items() unpacks both the key and the value simultaneously
for name, city in students.items():
    print(f"{name} -> {city}")

city_count = {}
for city in students.values():
    # If the city isn't in the dict yet, default it to 0 before adding 1
    city_count[city] = city_count.get(city, 0) + 1

print("\nCount in each city:")
for city, count in city_count.items():
    print(f"{city}: {count}")

All names: ['Aman', 'Riya', 'Vikas', 'Neha']
All city names: ['Dehradun', 'Delhi', 'Dehradun', 'Mumbai']

Student and city details:
Aman -> Dehradun
Riya -> Delhi
Vikas -> Dehradun
Neha -> Mumbai

Count in each city:
Dehradun: 2
Delhi: 1
Mumbai: 1


### Under the hood:

- **Gotchas:** Dictionary keys must be absolutely unique. If you add another `"Aman": "Pune"` to the dictionary, it will silently overwrite the first Aman heading to Dehradun. In real databases, you map User IDs as keys, not first names.
- **Complexity:** Dictionary lookups are $O(1)$ due to Hash Tables.

### ***Level up***
Managing the `city_count` tally with `.get(city, 0)` is standard, but DevOps and data engineering architectures rely on `collections.defaultdict`. It intercepts missing keys and initializes them instantly, stripping out the manual boilerplate logic.

In [35]:
from collections import defaultdict

# A dictionary that automatically initializes missing keys with an integer (0)
auto_city_count = defaultdict(int)

for city in students.values():
    # We can add directly without checking if the key exists!
    auto_city_count[city] += 1

print(f"DefaultDict Tally: {dict(auto_city_count)}")

DefaultDict Tally: {'Dehradun': 2, 'Delhi': 1, 'Mumbai': 1}


### ***Edge-Case Test:***
If you attempt to print `students.keys()` without wrapping it in `list()`, Python 3 returns a `dict_keys` view object (e.g., `dict_keys(['Aman', 'Riya'])`). Views update dynamically if the dictionary changes, but you cannot index them like `keys[0]`.

![alt text](gemini-svg_64.svg)

## Question 5: List of Dictionaries

**Task:** Store details of movies and perform filtering (released before 2015, made profit, by particular director).[cite: 6]

### ***The Dorm Movie Database***

### The Analogy
You have a hard drive packed with movies for the dorm. Instead of simple variables, you build a mini-database (JSON format). It's a single massive List, but every item inside that list is a Dictionary holding specific metadata about the movie. You write filtering algorithms to query this database—asking it to pull only the files that match your exact parameters.

In [36]:
# The Database (List of Dictionaries)
movies = [
    {"name": "Movie A", "year": 2012, "director": "Raj Mehra", "cost": 50, "collection": 80},
    {"name": "Movie B", "year": 2018, "director": "Anil Verma", "cost": 70, "collection": 65},
    {"name": "Movie C", "year": 2010, "director": "Raj Mehra", "cost": 40, "collection": 55},
]

print("--- Movies released before 2015 ---")
for movie in movies:
    if movie["year"] < 2015:
        print(movie["name"])

print("\n--- Box Office Hits (Profit) ---")
for movie in movies:
    if movie["collection"] > movie["cost"]:
        print(movie["name"])

print("\n--- Director Search ---")
search_director = "Raj Mehra"
for movie in movies:
    # .lower() neutralizes case sensitivity during the search
    if movie["director"].lower() == search_director.lower():
        print(movie["name"])

--- Movies released before 2015 ---
Movie A
Movie C

--- Box Office Hits (Profit) ---
Movie A
Movie C

--- Director Search ---
Movie A
Movie C


### Under the hood:

- **Gotchas:** Accessing `movie["collection"]` assumes every dictionary in the list possesses that exact key. If one movie file is corrupted and missing the `"collection"` key, the entire `for` loop will violently crash.
- **Complexity:** $O(N)$ for every individual filter loop.

In [37]:
# Executing database queries via list comprehension
profitable_movies = [m["name"] for m in movies if m.get("collection", 0) > m.get("cost", 0)]

print(f"Profitable Movies (One-Liner): {profitable_movies}")

Profitable Movies (One-Liner): ['Movie A', 'Movie C']


(Notice the .get("cost", 0) above—this guards against the missing key crash mentioned in the Gotchas!)

### ***Edge-Case Test:***
Floating point math in financial databases can be tricky. If `collection` is `50.0000001` and `cost` is `50.0`, the `>` operator correctly flags it as a profit. If they are exactly equal, they break even, which correctly fails the `>` check and omits the movie from the profit list.

### ***Level up***
Data structures like this (List of Dicts) are the exact format APIs use to send JSON payloads. Professional engineers don't write multi-line `for` loops to filter JSON; they use **List Comprehensions** to execute the query and generate the filtered list in a single, highly readable line.

![alt text](gemini-svg_65.svg)

# ***Experiment 7 — Functions***
                                                                                            -  Anshul Ghildiyal
                                                                                            -  590031643

## Question 1: Max and Min without built-ins

**Task:** Write a function to find maximum and minimum from a sequence without using built-in `max()` and `min()`.[cite: 7]

### ***The Midterm Grader***

### The Analogy
You are the Teaching Assistant grading midterms for the intro coding class. You don't have a magical button to instantly know the highest and lowest scores. Instead, you pick up the very first paper and declare it both the "highest" and "lowest" score you've seen so far. Then, you read through the rest of the stack one by one. If a paper is higher than your current top score, it takes the crown. If it's lower than the bottom score, it takes that crown.

In [38]:
def find_max_min(sequence):
    # Setting the baseline with the very first item
    maximum = sequence[0]
    minimum = sequence[0]

    # Looping through the rest of the items
    for value in sequence[1:]:
        if value > maximum:
            maximum = value
        if value < minimum:
            minimum = value

    return maximum, minimum

nums = [15, 3, 99, 42, 7]
mx, mn = find_max_min(nums)

print("Maximum:", mx)
print("Minimum:", mn)

Maximum: 99
Minimum: 3


### Under the hood:

- **Gotchas:** A huge beginner mistake is initializing `maximum = 0`. What if the sequence is `[-5, -10, -20]`? The maximum would stubbornly stay `0`, which isn't even in the list! Initializing with `sequence[0]` makes the logic bulletproof regardless of the data's range.
- **Complexity:** $O(N)$ time complexity. We traverse the sequence exactly once. $O(1)$ space complexity since we only store two tracking variables in memory.

### ***Level up***
In big data pipelines, sorting data is expensive. If you need the min and max to normalize data (like Min-Max Scaling in Machine Learning), doing it in one single pass $O(N)$ is optimal. We can improve our function's safety by handling cases where the data pipeline accidentally sends us an empty array.

In [39]:
def safe_find_max_min(sequence):
    if not sequence:
        raise ValueError("Data pipeline Error: Sequence is empty.")
    
    # Unpacking via an iterator to be more memory efficient
    iterator = iter(sequence)
    maximum = minimum = next(iterator)
    
    for value in iterator:
        if value > maximum: maximum = value
        elif value < minimum: minimum = value # 'elif' saves CPU cycles
            
    return maximum, minimum

print("Safe Extracted Tuple:", safe_find_max_min([15, 3, 99, 42, 7]))

Safe Extracted Tuple: (99, 3)


### ***Edge-Case Test:***
If you pass a list with identical numbers (e.g., `[5, 5, 5]`), the initial conditions set `maximum = 5` and `minimum = 5`. The loop conditions `>` and `<` will simply ignore the rest, correctly outputting `(5, 5)`.

![alt text](gemini-svg_71.svg)

## Question 2: Sum of cubes below n

**Task:** Write a function that takes a positive integer and returns sum of cubes of all positive integers smaller than it.[cite: 7]

### ***The Server Rack Capacity***

### The Analogy
You are the lead tech configuring the new AI server room. Rack 1 takes $1^3$ cooling units, Rack 2 takes $2^3$ cooling units, Rack 3 takes $3^3$, and so on. Before you install the massive $n$th rack, you need a function to dynamically calculate the cumulative cooling capacity already being consumed by all the smaller racks on the floor combined.

In [40]:
def sum_of_cubes_below(n):
    total = 0
    # range(1, n) iterates from 1 up to (n-1), perfectly excluding 'n'
    for i in range(1, n):
        total += i ** 3
    return total

n = 6
print(f"Sum of cubes below {n}:", sum_of_cubes_below(n))

Sum of cubes below 6: 225


### Under the hood:

- **Gotchas:** The wording strictly says "smaller than it". By utilizing Python's `range(1, n)`, the function is natively exclusive at the top boundary. If you used `range(1, n+1)`, you would incorrectly sum the $n$th cube as well.
- **Complexity:** $O(N)$ runtime. It requires iterating through every number and doing an arithmetic operation.

### ***Level up***
Running a `for` loop to calculate mathematical sequences is a waste of CPU cycles. Using pure mathematics (Faulhaber's formula), we can calculate the sum of consecutive cubes using a formula that drops the runtime from $O(N)$ to an instant $O(1)$.
Formula: $S = (\frac{m(m+1)}{2})^2$ (where $m = n - 1$).

In [41]:
def fast_sum_of_cubes(n):
    if n <= 1: return 0
    m = n - 1
    # Pure O(1) math, bypassing the loop completely
    return (m * (m + 1) // 2) ** 2

print(f"O(1) Math Sum:", fast_sum_of_cubes(6))

O(1) Math Sum: 225


### ***Edge-Case Test:***
If `n = 1`, the problem asks for positive integers strictly smaller than 1. Since none exist, the loop `range(1, 1)` will instantly exit and correctly return `0`.

![alt text](gemini-svg_72.svg)

## Question 3: Recursive print 1 to n

**Task:** Write a recursive function to print numbers from `1` to `n` (no loops).[cite: 7]

### ***The Chain of Command***

### The Analogy
Imagine the chain of command for getting a new club approved on campus. 
1. The freshman ($n=3$) hands the form to the sophomore ($n=2$).
2. The sophomore hands it to the junior ($n=1$).
3. The junior reaches the faculty advisor (the Base Case, $n=0$).
The advisor approves it and hands it back. The junior stamps it (`print(1)`), the sophomore stamps it (`print(2)`), and the freshman finally gets it back and stamps it (`print(3)`). Recursion burrows all the way to the bottom *before* it starts doing the actual work on the way back up.

In [42]:
def print_1_to_n(n):
    # The Base Case: The Faculty Advisor stopping the chain
    if n == 0:
        return
    
    # Burrowing down: Calling the function BEFORE printing
    print_1_to_n(n - 1)
    
    # Working on the way back up
    print(n, end=" ")

print_1_to_n(10)
print()

1 2 3 4 5 6 7 8 9 10 


### Under the hood:

- **Gotchas:** The placement of `print(n)` dictates the direction! If you place `print(n)` *before* the recursive call `print_1_to_n(n-1)`, it prints on the way down, resulting in `10 9 8 7...` instead.
- **Complexity:** $O(N)$ time complexity. But more importantly, $O(N)$ **Space Complexity**. Every recursive call gets stacked in the computer's RAM (Call Stack).

### ***Level up***
Standard recursion crashes if $N$ is too large (like $N=2000$). Python has a default recursion depth limit of 1000 to prevent your RAM from overflowing. If you are building deep tree-search algorithms in AIML, you must manually override this limit using the `sys` module, but proceed with extreme caution.

In [43]:
import sys

# Checking the default safety limit
print(f"Default Recursion Limit: {sys.getrecursionlimit()}")

# In extreme DevOps use-cases, we can raise it
sys.setrecursionlimit(2500)
print(f"New Limit Set: {sys.getrecursionlimit()}")

Default Recursion Limit: 3000
New Limit Set: 2500


### ***Edge-Case Test:***
If `n` is negative (e.g., `-5`), `n == 0` will never trigger. The function will plunge downwards (`-6, -7, -8...`) until it triggers a fatal `RecursionError`. A robust base case should check `if n <= 0: return`.

![alt text](gemini-svg_73.svg)

## Question 4: Recursive Fibonacci

**Task:** Write a recursive function to print Fibonacci series up to `n` terms.[cite: 7]

### ***The Campus Rumor Pyramid***

### The Analogy
Think of how a rumor spreads during finals week. You want to confirm the full story. To do so, you have to ask your two closest friends. But they don't know the full story either, so they each have to ask their two closest friends. This pyramid expands exponentially until it hits the original two freshmen (Base Case 0 and 1) who started it.

In [44]:
def fib(n):
    # Base cases: The original freshmen
    if n == 0:
        return 0
    if n == 1:
        return 1
    
    # Recursive case: Asking the two friends below you
    return fib(n - 1) + fib(n - 2)

terms = 8
print("Fibonacci series:")
for i in range(terms):
    print(fib(i), end=" ")
print()

Fibonacci series:
0 1 1 2 3 5 8 13 


### Under the hood:

- **Gotchas:** This looks elegant, but mathematically, it is a disaster. To calculate `fib(5)`, it has to calculate `fib(3)` twice, `fib(2)` three times, etc. The tree duplicates its work massively.
- **Complexity:** $O(2^N)$ Exponential Time. If you try to calculate `fib(40)`, your computer will freeze for several seconds. `fib(50)` might take hours.

### ***Level up***
Data structures utilize a technique called **Memoization** to cure this exponential nightmare. We give the function a "memo pad" (a cache). Before it asks a friend for a number, it checks the memo pad. If it has already calculated `fib(10)` earlier, it instantly retrieves the answer instead of splitting the universe into two new recursive branches.

In [45]:
from functools import lru_cache

# Caches the results of the recursive calls natively in memory
@lru_cache(maxsize=None)
def fast_fib(n):
    if n < 2: return n
    return fast_fib(n - 1) + fast_fib(n - 2)

# Instantly computes massive numbers, cutting O(2^N) down to O(N)
print(f"Fibonacci term 100: {fast_fib(100)}")

Fibonacci term 100: 354224848179261915075


### ***Edge-Case Test:***
Asking for negative terms (`fib(-1)`) will result in maximum recursion depth exceeded, as it steps downwards infinitely (`-2, -3, -4`). A protective wrapper checking `if n < 0: raise ValueError` is mandatory for production.

![alt text](gemini-svg_74.svg)

## Question 5: Lambda volume of cone

**Task:** Write a lambda function to find volume of a cone.[cite: 7]

### ***The Espresso Shot***

### The Analogy
A standard Python function (`def`) is like the full barista setup at the campus café. It takes time, space, names, and formal parameters. A `lambda` function is like the dorm room espresso machine. It's an anonymous, one-off, single-line shot of logic. It executes its math instantly and disappears, perfect for situations where naming a full function feels like overkill.

In [46]:
import math

# Lambda syntax: lambda arguments: expression
cone_volume = lambda r, h: (1 / 3) * math.pi * r ** 2 * h

# Calling the lambda just like a normal function
print(f"Volume of cone: {cone_volume(3, 5):.2f}")

Volume of cone: 47.12


### Under the hood:

- **Gotchas:** Assigning a lambda to a variable (`cone_volume = lambda...`) actually violates Python's PEP 8 style guide. Lambdas are meant to be *anonymous*. If you are giving it a name, you should just use `def`. However, lab manuals use this to teach the syntax visually.
- **Complexity:** $O(1)$ computation.

### ***Level up***
Where do lambdas truly belong? Inside higher-order functions! If you have a massive dataset of 5,000 different cone dimensions (tuples of `(radius, height)`), you can pass a lambda directly inside a `map()` function to process the entire array instantly without ever declaring a formal loop.

In [47]:
import math

cone_data = [(2, 4), (3, 5), (4, 6)] # (radius, height)

# Passing an anonymous lambda into the map() engine
volumes = list(map(lambda dimensions: (1/3) * math.pi * dimensions[0]**2 * dimensions[1], cone_data))

print(f"Mapped Volumes: {[round(v, 2) for v in volumes]}")

Mapped Volumes: [16.76, 47.12, 100.53]


### ***Edge-Case Test:***
Negative heights and radii mathematically compute without errors because the radius is squared (`-3 ** 2 = 9`) and the math flows. However, this violates the laws of physics. If constraints matter, a lambda is too small; you need a `def` function with `if r < 0: raise Error`.

![alt text](gemini-svg_75.svg)

## Question 6: Lambda max and min tuple

**Task:** Write a lambda function to return tuple of maximum and minimum from a list.[cite: 7]

### ***The Grading Curve***

### The Analogy
You are trying to figure out if you passed your algorithms final. The professor writes a quick lambda script to instantly extract the lowest score in the class and the highest score in the class, packaging them tightly into an unchangeable Tuple, so the parameters for the grading curve are locked in place.

In [48]:
data = [10, 6, 8, 90, 12, 56]

# Lambda taking a list and returning a (max, min) tuple
max_min_tuple = lambda values: (max(values), min(values))

print("Curve Bounds (Max, Min):", max_min_tuple(data))

Curve Bounds (Max, Min): (90, 6)


### Under the hood:

- **Gotchas:** This lambda traverses the list *twice*. `max(values)` loops through all $N$ elements, and then `min(values)` loops through all $N$ elements again. For 6 numbers, it's fine. For 6 million stock market ticks, it's inefficient.
- **Complexity:** $O(2N)$ time complexity.

### ***Level up***
Lambdas are the secret weapon for custom sorting. If you have a list of complex dictionary objects (like university students), and you want to sort them *only* by their GPA, a lambda provides the exact sorting key instantly without needing a bulky helper function.

In [49]:
students = [
    {"name": "Alpha", "gpa": 3.8},
    {"name": "Bravo", "gpa": 2.9},
    {"name": "Charlie", "gpa": 4.0}
]

# Using a lambda as the custom key for the sorted() engine
sorted_students = sorted(students, key=lambda s: s["gpa"], reverse=True)

print("Top Student:", sorted_students[0]["name"])

Top Student: Charlie


### ***Edge-Case Test:***
Passing an empty list `[]` to the lambda will result in a fatal `ValueError: max() arg is an empty sequence`. Lambdas don't handle try/except blocks gracefully.

![alt text](gemini-svg_76.svg)

## Question 7: Argument Types

**Task:** Write functions to explain: Keyword arguments, Default arguments, Variable length arguments.[cite: 7]

### ***The Hackathon Registration Portal***

### The Analogy
You are building the registration API for the campus hackathon. 
*   **Default Arguments:** The portal auto-sets your `location` to "Main Campus" unless you explicitly override it.
*   **Keyword Arguments:** You can fill out the web form completely out of order (entering your `age` before your `name`), and the system will safely map the data.
*   **Variable Length Arguments (`*args`):** You don't know if a team will have 1 member or 10. `*args` throws a net that catches as many teammates as you input, packing them all safely into a single Tuple bag.

In [50]:
# 1. Keyword Argument Logic (Order doesn't matter)
def student_info(name, age):
    print(f"Hacker: {name}, Age: {age}")

student_info(age=20, name="Ravi") # Order swapped, safely mapped!

# 2. Default Argument Logic (Pre-filled form)
def greet(name, message="Welcome to the Hackathon"):
    print(f"{name}: {message}")

greet("Riya") # Falls back to default
greet("Riya", "System Override") # Overrides default

# 3. Variable Length (*args) (Catching multiple items)
def total_marks(*marks):
    # *marks packages all inputted numbers into a Tuple: (78, 85, 90...)
    return sum(marks)

print("Team Combined Score:", total_marks(78, 85, 90, 88, 76))

Hacker: Ravi, Age: 20
Riya: Welcome to the Hackathon
Riya: System Override
Team Combined Score: 417


### Under the hood:

- **Gotchas:** Default arguments must **always** follow non-default arguments in the function definition. If you write `def greet(message="Hi", name):`, Python throws a `SyntaxError`. The interpreter needs non-defaults aligned to the front to map them correctly.
- **Complexity:** `*args` packs inputs into a Tuple, taking $O(N)$ space in memory where $N$ is the amount of arguments passed.

### ***Level up***
`*args` catches rogue lists, but what if you need to catch unknown dictionary inputs (like an API sending unpredictable user profiles)? You use `**kwargs` (Keyword Arguments). This catches everything structured as `key=value` and safely packs it into a Python Dictionary.

In [51]:
# Packing unlimited Key/Value pairs into a Dictionary
def build_profile(**kwargs):
    print("\nProcessing Dynamic Profile:")
    for key, value in kwargs.items():
        print(f"  {key.upper()}: {value}")

# We can pass as many custom fields as we want
build_profile(name="Vegapunk", major="DevOps", clearance_level=5, campus="Main")


Processing Dynamic Profile:
  NAME: Vegapunk
  MAJOR: DevOps
  CLEARANCE_LEVEL: 5
  CAMPUS: Main


### ***Edge-Case Test:***
A notorious Python bug involves using mutable objects as default arguments: `def add_item(item, bag=[])`. The `[]` memory block is allocated *once* when the function is defined. Subsequent calls will pile items into the same shared bag, rather than creating a new empty bag. Always use `bag=None` as the default.

![alt text](gemini-svg_77.svg)

# ***Experiment 8 — File Handling and Exception Handling***
                                                                                            -  Anshul Ghildiyal
                                                                                            -  590031643

## Question 1: Name metrics from a file

**Task:** Add a few names in `name.txt`, then count total names, count names starting with a vowel, and find the longest name.[cite: 8]

### ***The Dorm Party Guest List***

### The Analogy
You are hosting a massive dorm party and writing the guest list down on a physical clipboard (the `.txt` file). If you just kept the names in your head (RAM), you'd forget them the moment you went to sleep. By writing them to the hard drive, the data persists. Later, the bouncer (your script) reads the clipboard line-by-line to figure out how many people are coming, who gets VIP access (vowels), and whose name is the hardest to pronounce (the longest string).

In [52]:
names = ["Aarav", "Ishita", "Rahul", "Omkar", "Esha", "Vivek"]

# 1. Writing to the clipboard (File)
with open("name.txt", "w", encoding="utf-8") as file:
    for name in names:
        file.write(name + "\n")

# 2. Bouncer reading the clipboard
with open("name.txt", "r", encoding="utf-8") as file:
    # .strip() removes the hidden \n newline characters from the file
    stored_names = [line.strip() for line in file if line.strip()]

vowels = tuple("AEIOUaeiou")
count_names = len(stored_names)
count_vowel_start = sum(1 for name in stored_names if name.startswith(vowels))
longest_name = max(stored_names, key=len) if stored_names else None

print("Names in file:", stored_names)
print("Count of names:", count_names)
print("Names starting with vowel:", count_vowel_start)
print("Longest name:", longest_name)

Names in file: ['Aarav', 'Ishita', 'Rahul', 'Omkar', 'Esha', 'Vivek']
Count of names: 6
Names starting with vowel: 4
Longest name: Ishita


### Under the hood:

- **Gotchas:** When writing to a file, Python doesn't automatically add newlines. If you forget `+ "\n"`, your file will look like `AaravIshitaRahul`. When reading, that `\n` is still attached to the string! You must use `.strip()` to cleanly extract the name.[cite: 8]
- **Complexity:** $O(N)$ where $N$ is the number of lines in the file. `with open()` is a **Context Manager**—it guarantees the file is safely closed when the block ends, even if the program crashes halfway through.

### ***Level up***
If your party guest list has 10 million names, reading them all into a list `stored_names` at once will cause your computer's RAM to explode. To handle big data, DevOps engineers use **lazy evaluation**. We read and process the file exactly one line at a time, keeping RAM usage near zero.

In [53]:
# Big Data Optimization: Processing without storing the whole file in RAM
total_guests = 0
longest = ""

with open("name.txt", "r", encoding="utf-8") as file:
    for line in file:
        clean_name = line.strip()
        if not clean_name: continue
        
        total_guests += 1
        if len(clean_name) > len(longest):
            longest = clean_name

print(f"Memory-Safe Total: {total_guests} | Longest: {longest}")

Memory-Safe Total: 6 | Longest: Ishita


### ***Edge-Case Test:*** 
If the file is completely empty, Python's built-in `max()` function will trigger a fatal `ValueError: max() arg is an empty sequence`. The code utilizes an inline guard `max(...) if stored_names else None` to safely bypass this crash.

![alt text](gemini-svg_81.svg)

## Question 2: Numeric File Aggregation

**Task:** Store integers in a file and then find the max, find the average, and count numbers greater than 100.[cite: 8]

### ***The Gym Progression Log***

### The Analogy
You are tracking your deadlift progression. Every week, you jot your 1-Rep Max into a raw text file on your computer. When the semester ends, you want a script to parse that file to tell you your absolute highest lift, your average volume, and how many times you broke the 100-pound barrier. The script acts as your automated personal trainer.

In [54]:
numbers = [45, 120, 5, 300, 88, 150, 99]

# Logging the lifts to the file
with open("numbers.txt", "w", encoding="utf-8") as file:
    for number in numbers:
        file.write(f"{number}\n")

# Reading the logs back into the system
with open("numbers.txt", "r", encoding="utf-8") as file:
    # We MUST cast the text file strings back into integers
    values = [int(line.strip()) for line in file if line.strip()]

maximum_number = max(values)
average_number = sum(values) / len(values)
greater_than_100 = sum(1 for number in values if number > 100)

print("Logged Numbers:", values)
print("Max Lift:", maximum_number)
print("Average Lift:", round(average_number, 2))
print("Sessions > 100 lbs:", greater_than_100)

Logged Numbers: [45, 120, 5, 300, 88, 150, 99]
Max Lift: 300
Average Lift: 115.29
Sessions > 100 lbs: 3


### Under the hood:

- **Gotchas:** Text files have zero concept of math. They store everything as characters. The number `300` is saved as the text string `"300\n"`. If you try to run `max()` without casting via `int()`, Python will evaluate them alphabetically, which creates horrific logical errors (alphabetically, `"99"` is "larger" than `"150"` because 9 comes after 1).[cite: 8]
- **Complexity:** $O(N)$ for writing, and $O(N)$ for mapping strings to ints during the read phase.

### ***Level up***
What if your roommate borrows your computer and accidentally types "Missed workout" into `numbers.txt`? Your `int()` cast will violently crash with a `ValueError`. Professional pipelines use safe-parsing wrappers to ignore corrupted data lines.

In [55]:
safe_values = []

with open("numbers.txt", "r") as file:
    for line in file:
        try:
            # Attempts to convert to integer
            safe_values.append(int(line.strip()))
        except ValueError:
            # If it's corrupt text like "Missed", ignore it and move on
            print(f"[WARNING] Skipping corrupt log entry: {line.strip()}")

print(f"Safely Extracted Math Data: {safe_values}")

Safely Extracted Math Data: [45, 120, 5, 300, 88, 150, 99]


### ***Edge-Case Test:*** 
A file full of blank lines (e.g., hitting "Enter" 5 times) will yield empty strings `""`. Trying to cast `int("")` causes a crash. The `if line.strip()` condition in the list comprehension elegantly ignores these ghost lines.

![alt text](gemini-svg_82.svg)

## Question 3: Structured Data Parsing

**Task:** Read a file storing city details as `city_name population area`. Display details, filter by population > 10, and sum all areas.[cite: 8]

### ***The Database Extraction***

### The Analogy
You downloaded an old-school text database of university campuses. The data isn't in a nice Excel sheet; it's just raw rows separated by spaces. You have to write an extraction tool that chops each row into three distinct pieces (Name, Population, Area), converts the math parts into floats, and structures them properly so you can actually run analytical queries on them.

In [56]:
city_records = [
    ("Dehradun", 5.78, 308.20),
    ("Delhi", 190.00, 1484.00),
    ("Mumbai", 124.00, 603.40),
]

# Simulating the raw text dump creation
with open("city.txt", "w", encoding="utf-8") as file:
    for city, population, area in city_records:
        file.write(f"{city} {population} {area}\n")

parsed_cities = []
# The Extraction Engine
with open("city.txt", "r", encoding="utf-8") as file:
    for line in file:
        parts = line.split() # Chops the line by spaces into a list
        if len(parts) == 3:
            city = parts[0]
            population = float(parts[1]) # Casting to math objects
            area = float(parts[2])
            parsed_cities.append((city, population, area))

print("All extracted details:")
for city, population, area in parsed_cities:
    print(f"{city}: pop={population} lakh, area={area} sq km")

# Querying the structured data
megacities = [city for city, population, _ in parsed_cities if population > 10]
total_area = sum(area for _, _, area in parsed_cities)

print("\nMegacities (>10 lakhs):", megacities)
print("Sum of all areas:", round(total_area, 2), "sq km")

All extracted details:
Dehradun: pop=5.78 lakh, area=308.2 sq km
Delhi: pop=190.0 lakh, area=1484.0 sq km
Mumbai: pop=124.0 lakh, area=603.4 sq km

Megacities (>10 lakhs): ['Delhi', 'Mumbai']
Sum of all areas: 2395.6 sq km


### Under the hood:

- **Gotchas:** The line `city, population, area = parts` is called Tuple Unpacking. It's beautiful, but if a city name has a space in it (e.g., `"New York 8.4 783"`), `.split()` cuts it into 4 pieces `["New", "York", "8.4", "783"]`. The unpacking logic will shatter with a `ValueError: too many values to unpack`.
- **Complexity:** $O(N)$ string splitting and float conversion.

### ***Level up***
Manually splitting text files is brittle. If you are dealing with real-world tabular data (CSV, TSV), use Python's built-in `csv` module. It safely handles edge cases like spaces inside names if the strings are properly quoted (e.g., `"New York",8.4,783`).

In [57]:
import csv

# Professional CSV parsing handles internal spaces and quotes natively
def parse_csv_safely(filepath):
    results = []
    with open(filepath, 'r') as csvfile:
        # Delimiter can be spaces or commas
        reader = csv.reader(csvfile, delimiter=' ')
        for row in reader:
            if len(row) == 3:
                results.append({"city": row[0], "pop": float(row[1])})
    return results

print("CSV Parser Active.")

CSV Parser Active.


### ***Edge-Case Test:*** 
The `_` in `for city, population, _ in parsed_cities` is a "throwaway" variable. It tells Python and other developers: "I am unpacking three variables to avoid structural errors, but I have absolutely no intention of using the 3rd variable (area) in this specific logic block."

![alt text](gemini-svg_83.svg)

## Question 4: Exception Handling for Math

**Task:** Input test cases of `a b`, perform integer division `a/b`, and handle exceptions for `ZeroDivisionError` and `ValueError`.[cite: 8]

### ***The Automated Exam Grader***

### The Analogy
You built a Python script to automatically grade math exams for the university. However, students type wild things. Some try to divide by zero. Others type a dollar sign (`$`) instead of a number. If your script crashes on Student #2, the remaining 500 students don't get graded. You use `try/except` blocks as a blast shield. When a student enters corrupt logic, the blast shield absorbs the error, flags it, and safely moves to the next exam without shutting the server down.

In [58]:
raw_input_data = "3\n1 0\n2 $\n3 1"

# Simulating reading lines from an input file or standard input
lines = raw_input_data.strip().splitlines()
n = int(lines[0])

for line in lines[1:n + 1]:
    a_text, b_text = line.split()
    
    # The Blast Shield
    try:
        result = int(a_text) // int(b_text)
        print("Success:", result)
    except ZeroDivisionError as error:
        print("Error Code: Div by Zero! ->", error)
    except ValueError as error:
        print("Error Code: Bad Character! ->", error)

Error Code: Div by Zero! -> integer division or modulo by zero
Error Code: Bad Character! -> invalid literal for int() with base 10: '$'
Success: 3


### Under the hood:

- **Gotchas:** The order of `except` blocks matters. You should always catch specific errors (like `ZeroDivisionError`) first. If you place a generic `except Exception:` at the top, it acts as a black hole, catching absolutely everything, making it impossible to trigger your specific error handlers below it.[cite: 8]
- **Complexity:** Try/except blocks have almost zero performance overhead in Python when no exception is raised.

### ***Level up***
If you are running a server, printing errors to the terminal is useless because the terminal clears when you close it. DevOps uses the `logging` module to silently intercept these exceptions and write them permanently to a `.log` file, preserving the exact timestamp and context of the crash.

In [59]:
import logging

# Configures the system to write errors silently to a file instead of the screen
logging.basicConfig(filename='grader_errors.log', level=logging.ERROR)

def safe_divide(a, b):
    try:
        return int(a) // int(b)
    except Exception as e:
        # Logs the exact stack trace for developers to fix later
        logging.error(f"Failed to divide {a} by {b}. Reason: {e}")
        return None

safe_divide("5", "0")
print("Error safely logged to grader_errors.log")

Error safely logged to grader_errors.log


![alt text](gemini-svg_84.svg)

## Question 5: Creating Custom Exceptions

**Task:** Create multiple suitable exceptions for a file handling program.[cite: 8]

### ***The Campus Security Protocol***

### The Analogy
Standard Python errors are like a general campus fire alarm—they tell you something is wrong, but not *what*. You are designing the backend for the university portal. You build **Custom Exceptions**—like a specific alert that says `UnauthorizedAccessError` or `CorruptStudentFileError`. When the system catches this specific alert, it knows exactly which protocol to execute (e.g., locking the account vs. asking the student to re-upload the file).

In [60]:
# Defining custom security protocols by inheriting from Python's base Exception
class EmptyFileError(Exception):
    pass

class InvalidRecordError(Exception):
    pass

def read_student_marks(file_name):
    # Simulating file reading logic
    lines = [] # Simulating an empty file scenario
    
    if not lines:
        # Firing our custom flare into the sky
        raise EmptyFileError(f"CRITICAL: {file_name} is completely empty.")
        
    for line in lines:
        parts = line.split(",")
        if len(parts) != 2:
            raise InvalidRecordError(f"Format corrupted in line: '{line}'")

# Execution
try:
    data = read_student_marks("missing_grades.txt")
except EmptyFileError as error:
    print(f"Triggered Protocol: Request file re-upload. -> {error}")
except InvalidRecordError as error:
    print(f"Triggered Protocol: Run format repair tool. -> {error}")

Triggered Protocol: Request file re-upload. -> CRITICAL: missing_grades.txt is completely empty.


### Under the hood:

- **Gotchas:** Your custom class *must* inherit from `Exception` (or a subclass like `ValueError`). If you just write `class EmptyFileError: pass`, Python's `raise` keyword will violently reject it, because it is just a normal object, not an error payload.[cite: 8]
- **Complexity:** Creating custom classes introduces minimal architectural overhead but massive debugging value.

### ***Level up***
A basic `pass` block works, but professional custom exceptions accept initialization parameters. We can supercharge our `InvalidRecordError` to capture and store the exact line number where the database failed, allowing the front-end dashboard to tell the user exactly where to fix their typo.

In [61]:
class PrecisionRecordError(Exception):
    def __init__(self, line_number, message="Database formatting error"):
        self.line_number = line_number
        self.message = message
        # Overriding the default string representation of the error
        super().__init__(f"Row {self.line_number} Failed: {self.message}")

# We can raise it with specific context
try:
    raise PrecisionRecordError(line_number=42, message="Missing comma")
except PrecisionRecordError as e:
    print(f"System Alert: {e}")

System Alert: Row 42 Failed: Missing comma


### ***Edge-Case Test:***
If you are inside an `except` block catching a generic error, and you want to transform it into your custom error, you should use `raise CustomError from e`. The `from e` syntax preserves the original traceback so developers can see the entire history of the crash, preventing the original root cause from being swallowed.

![alt text](gemini-svg_85.svg)

# ***Experiment 9 — Classes and Objects***
                                                                                            -  Anshul Ghildiyal
                                                                                            -  590031643

## Question 1: Create a Student Class

**Task:** Create a `Student` class with `name`, `sap_id`, and marks in `phy`, `chem`, `maths`. Create 3 objects and display details of all students.[cite: 9]

### ***The Blank ID Card Template***

### The Analogy
You are volunteering at the university registrar's office. You don't hand-draw a new ID card for every single student. You design a master template (the Class). It has empty slots for a Name, a SAP ID, and their current grades. When a freshman walks in, you just take their data, stamp it into the template, and print a physical card (the Object). You can use one template to stamp out thousands of unique student cards.

In [62]:
class Student:
    # The __init__ constructor: This runs the moment a new card is stamped
    def __init__(self, name, sap_id, marks):
        # 'self' attaches the data strictly to the specific card being printed
        self.name = name
        self.sap_id = sap_id
        self.marks = marks

    def display(self):
        print(f"Name: {self.name} | SAP ID: {self.sap_id} | Marks: {self.marks}")

# Stamping out 3 unique objects from the same template
students = [
    Student("Ray", "500069944", {"phy": 78, "chem": 82, "maths": 91}),
    Student("Aman", "5001", {"phy": 65, "chem": 70, "maths": 80}),
    Student("Riya", "5002", {"phy": 88, "chem": 92, "maths": 85})
]

print("--- University Database ---")
for student in students:
    student.display()

--- University Database ---
Name: Ray | SAP ID: 500069944 | Marks: {'phy': 78, 'chem': 82, 'maths': 91}
Name: Aman | SAP ID: 5001 | Marks: {'phy': 65, 'chem': 70, 'maths': 80}
Name: Riya | SAP ID: 5002 | Marks: {'phy': 88, 'chem': 92, 'maths': 85}


### Under the hood:

- **Gotchas:** Forgetting the `self` parameter inside the class methods is the #1 reason OOP code crashes. `self` is Python's way of saying, "Hey, apply this action to the *specific* student object currently calling the method, not the master blueprint."[cite: 9]
- **Complexity:** $O(1)$ time and space complexity for object instantiation. Creating an object is virtually instantaneous.

### ***Level up***
Standard classes require a lot of boilerplate code (like manually typing `self.name = name` repeatedly). Modern Python development utilizes **Dataclasses**. They auto-generate the `__init__`, `__repr__`, and `__eq__` methods behind the scenes, leaving your codebase incredibly sleek.

In [63]:
from dataclasses import dataclass

# The @dataclass decorator acts as an automated code-writer
@dataclass
class ModernStudent:
    name: str
    sap_id: str
    marks: dict
    
    def display(self):
         print(f"[{self.sap_id}] {self.name} - {self.marks}")

# Instantiation works exactly the same!
top_student = ModernStudent("Ray", "500069944", {"phy": 95, "chem": 90, "maths": 99})
top_student.display()

[500069944] Ray - {'phy': 95, 'chem': 90, 'maths': 99}


### ***Edge-Case Test:*** 
What happens if you try to `print(student)` directly instead of `student.display()`? A standard class will print an ugly memory address like `<__main__.Student object at 0x7f...>`, but a Dataclass will beautifully print `ModernStudent(name='Ray', sap_id='500069944'...)`.

![alt text](gemini-svg_91.svg)

## Question 2: Advanced Methods and Aggregation

**Task:** Add methods to calculate the percentage, return the pass/fail result, and write an external function to find the class average.[cite: 9]

### ***The Automated Grading Pipeline***

### The Analogy
Instead of having the professors manually calculate if a student passed their AIML classes, you bake the grading logic directly into the Student template. Now, every single ID card basically acts like a smart-contract that can grade itself. The `class_average` function acts as the Dean's dashboard, sweeping across all the individual smart-cards to generate a global metric.

In [65]:
class StudentRecord:
    def __init__(self, name, sap_id, marks):
        self.name = name
        self.sap_id = sap_id
        self.marks = marks

    def display(self):
        print(f"[{self.sap_id}] {self.name} | Marks: {self.marks}")

    def marks_percentage(self):
        # Dynamically calculates based on the length of the dictionary
        return sum(self.marks.values()) / len(self.marks)

    def result(self):
        # all() evaluates True only if every single mark is > 40
        return "Pass" if all(mark > 40 for mark in self.marks.values()) else "Fail"

# The Aggregator Function (External to the class)
def class_average(records):
    total_percentage = sum(record.marks_percentage() for record in records)
    return total_percentage / len(records)

# Pipeline Data
records = [
    StudentRecord("Ray", "500069944", {"phy": 78, "chem": 67, "maths": 81}),
    StudentRecord("Kunal", "5002", {"phy": 88, "chem": 92, "maths": 85}),
    StudentRecord("Meera", "5003", {"phy": 39, "chem": 73, "maths": 64}) # Physics < 40
]

for record in records:
    print(f"{record.name} | Score: {record.marks_percentage():.2f}% | Status: {record.result()}")

print(f"\n[Global Class Average]: {class_average(records):.2f}%")

Ray | Score: 75.33% | Status: Pass
Kunal | Score: 88.33% | Status: Pass
Meera | Score: 58.67% | Status: Fail

[Global Class Average]: 74.11%


### Under the hood:

- **Gotchas:** Calling `len(self.marks)` assumes the dictionary isn't empty. If a student enrolled but has zero grades `{}` entered yet, `len()` returns 0, and the script violently crashes with a `ZeroDivisionError`.[cite: 9]
- **Complexity:** `marks_percentage()` operates in $O(M)$ where $M$ is the number of subjects. `class_average()` operates in $O(S \times M)$ where $S$ is the number of students.

### ***Level up***
In professional codebases, calling `student.marks_percentage()` as a function feels clunky because a percentage is an *attribute* of the student, not an *action* they are performing. We use the `@property` decorator to trick Python into treating the method exactly like a standard variable.

In [66]:
class SmartStudent:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    @property
    def percentage(self):
        if not self.marks: return 0.0 # Guard clause against division by zero!
        return sum(self.marks.values()) / len(self.marks)

student = SmartStudent("Ray", {"AIML": 95, "DevOps": 88})
# Notice there are no parentheses () after percentage! It acts like a variable.
print(f"Dynamic Property Access: {student.percentage}%")

Dynamic Property Access: 91.5%


### ***Edge-Case Test:***
If you pass an empty dictionary to `all(mark > 40 for mark in self.marks.values())`, the `all()` function natively evaluates to `True`. Meaning a student with literally zero grades would default to "Pass". You must add `if not self.marks: return "Fail"`.

![alt text](gemini-svg_92.svg)

## Question 3: Types of Inheritance

**Task:** Create programs to implement single, multilevel, and multiple inheritance.[cite: 9]

### ***The Campus Persona Stack***

### The Analogy
Inheritance is about passing down abilities natively. 
*   **Single Inheritance:** The `DevOpsStudent` inherits basic terminal access from the overarching `UniversityStudent` class.
*   **Multilevel Inheritance:** Hardware hierarchy. A base `TechDevice` passes power functions down to a `MacSystem`, which passes macOS functions down to your specific `MacBookM5`.
*   **Multiple Inheritance:** You are the synergy of your disciplines. You inherit deep technical knowledge from your `AIMLMajor` class, and you inherit physical strength from your `FitnessAthlete` class, combining them both into your `ByteAndBarbell` persona.

In [67]:
# --- 1. Single Inheritance ---
class UniversityStudent:
    def access_library(self):
        print("[Single] Accessing main campus library database.")

class DevOpsStudent(UniversityStudent):
    def deploy_server(self):
        print("[Single] Deploying AWS EC2 instance.")

# --- 2. Multilevel Inheritance ---
class TechDevice:
    def power_on(self):
        print("[Multilevel] Device booting up...")

class MacSystem(TechDevice):
    def load_macos(self):
        print("[Multilevel] Loading macOS kernel...")

class MacBookM5(MacSystem):
    def train_model(self):
        print("[Multilevel] Training AIML models on M5 silicon...")

# --- 3. Multiple Inheritance ---
class AIMLMajor:
    def code_pipeline(self):
        print("[Multiple] Architecting multi-model data pipelines.")

class FitnessAthlete:
    def lift_heavy(self):
        print("[Multiple] Executing 5x5 compound sets.")

class ByteAndBarbell(AIMLMajor, FitnessAthlete):
    def create_content(self):
        print("[Multiple] Recording authentic voiceovers for the audience.")

# Execution
print("--- Architecture Demos ---")
dev_ops = DevOpsStudent()
dev_ops.access_library() # Inherited

laptop = MacBookM5()
laptop.power_on() # Inherited from Grandparent
laptop.load_macos() # Inherited from Parent

ray = ByteAndBarbell()
ray.code_pipeline() # Inherited from Parent 1
ray.lift_heavy() # Inherited from Parent 2
ray.create_content() # Native method

--- Architecture Demos ---
[Single] Accessing main campus library database.
[Multilevel] Device booting up...
[Multilevel] Loading macOS kernel...
[Multiple] Architecting multi-model data pipelines.
[Multiple] Executing 5x5 compound sets.
[Multiple] Recording authentic voiceovers for the audience.


### Under the hood:

- **Gotchas:** Multiple inheritance triggers the infamous **Diamond Problem**. If both `AIMLMajor` and `FitnessAthlete` possessed a method called `execute()`, which one would the child class use? Python relies on **MRO (Method Resolution Order)**, reading the parents strictly from left-to-right.[cite: 9]
- **Complexity:** Method lookups climb the inheritance tree dynamically, taking $O(D)$ time where $D$ is the depth of the inheritance tree.

### ***Level up***
If a child class overrides its parent's `__init__` constructor, the parent class's properties are destroyed unless explicitly salvaged. You must use `super().__init__()` to securely pass the initialization variables back up the chain.

In [69]:
class BaseStudent:
    def __init__(self, name):
        self.name = name

class GradStudent(BaseStudent):
    def __init__(self, name, thesis_topic):
        # We MUST call super() so the Parent handles the 'name' logic
        super().__init__(name)
        self.thesis_topic = thesis_topic

student = GradStudent("Ray", "Automated Trading Algorithms")
print(f"Inherited Name: {student.name} | Thesis: {student.thesis_topic}")

Inherited Name: Ray | Thesis: Automated Trading Algorithms


### ***Edge-Case Test:***
You can instantly check a class's internal resolution logic by printing `ByteAndBarbell.mro()`. It outputs the exact sequence Python will follow when searching for a requested method, allowing you to debug inheritance conflicts flawlessly.

![alt text](gemini-svg_93.svg)

## Question 4: Method Overriding

**Task:** Create a class to implement method overriding.[cite: 9]

### ***Project Vegapunk's Upgrade***

### The Analogy
Your professor gives you a base template called `TradingAlgorithm`. It has an `execute_trade()` function that just blindly buys AAPL stock at 9 AM. You create a child class called `ProjectVegapunk` that inherits from it. But instead of letting the base algorithm blindly buy stock, you write a completely new `execute_trade()` function inside your child class. When the system calls that method, your advanced AI implementation crushes and replaces the generic parent method.

In [70]:
class BaseAlgorithm:
    def execute_trade(self):
        print("[Base Algo] Executing standard market order.")

class ProjectVegapunk(BaseAlgorithm):
    # This identically named method OVERRIDES the parent method
    def execute_trade(self):
        print("[Vegapunk Algo] Fetching morning data retrieval models...")
        print("[Vegapunk Algo] Running sentiment analysis. Executing paper trade.")

generic_bot = BaseAlgorithm()
advanced_bot = ProjectVegapunk()

print("--- Triggering Base System ---")
generic_bot.execute_trade()

print("\n--- Triggering Upgraded System ---")
advanced_bot.execute_trade()

--- Triggering Base System ---
[Base Algo] Executing standard market order.

--- Triggering Upgraded System ---
[Vegapunk Algo] Fetching morning data retrieval models...
[Vegapunk Algo] Running sentiment analysis. Executing paper trade.


### Under the hood:

- **Gotchas:** This relies heavily on exact spelling. If you accidentally name the child method `execute_trades()` (with an 's'), it won't override anything! It will just create a completely new method, and if you call `execute_trade()`, the parent's generic code will unexpectedly execute.[cite: 9]
- **Complexity:** Python checks the namespace of the current object first. Finding the method immediately resolves it in $O(1)$ without needing to traverse the MRO tree.

### ***Level up***
In large architectures, how do you force a teammate to override a method so they don't accidentally rely on the generic version? You use the `abc` (Abstract Base Class) module. It turns the parent into a strict contract that will crash the code if the child fails to supply an override.

In [71]:
from abc import ABC, abstractmethod

class StrictBlueprint(ABC):
    @abstractmethod
    def mandatory_override(self):
        pass # This forces any child class to build this method

class CompliantChild(StrictBlueprint):
    def mandatory_override(self):
        print("Contract fulfilled. System stable.")

compliant = CompliantChild()
compliant.mandatory_override()

Contract fulfilled. System stable.


### ***Edge-Case Test:***
If you override a method, but you still want the parent's logic to run *in addition* to your new logic, you invoke it inside the child via `super().execute_trade()`. This executes both sequentially.

![alt text](gemini-svg_94.svg)

## Question 5: Operator Overloading

**Task:** Create a class for operator overloading which adds two `Point` objects where each point has `x` and `y` values.[cite: 9]

### ***The Campus Drone Pathing***

### The Analogy
Python natively understands that `5 + 5` equals `10`. But it has absolutely no idea what it means when you type `LocationA + LocationB`. You are programming a navigation drone that moves on an `(x, y)` grid across the campus quad. By "overloading" the `+` operator, you are essentially wiring the `+` button on your keyboard to a custom motor function that adds the GPS coordinates together logically.

In [72]:
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    # Magic Dunder Method: Hijacks the '+' symbol
    def __add__(self, other):
        # We create and return an entirely NEW Point object
        return Point(self.x + other.x, self.y + other.y)

    # Magic Dunder Method: Hijacks the print() function for this object
    def __repr__(self):
        return f"Point(x={self.x}, y={self.y})"

# P1 is the drone's start location, P2 is the movement vector
p1 = Point(10, 20)
p2 = Point(12, 15)

# Python sees '+', checks the object, and routes it to __add__
p3 = p1 + p2

print("Location 1:", p1)
print("Vector   2:", p2)
print("Final Loc :", p3)

Location 1: Point(x=10, y=20)
Vector   2: Point(x=12, y=15)
Final Loc : Point(x=22, y=35)


### Under the hood:

- **Gotchas:** Magic methods (like `__add__`) should almost *always* return a brand new instance of the class rather than modifying `self.x` directly. If you modify `self.x`, calling `p3 = p1 + p2` will permanently corrupt `p1`'s data in the database.[cite: 9]
- **Complexity:** $O(1)$ computation.

### ***Level up***
What happens if someone accidentally types `p1 + 50`? The drone software will crash because `50` (an integer) doesn't have an `.x` or `.y` attribute. We level up our `__add__` method by injecting strict type verification.

In [73]:
class SafePoint:
    def __init__(self, x, y):
        self.x, self.y = x, y

    def __add__(self, other):
        # Verifies the 'other' object is actually a SafePoint
        if not isinstance(other, SafePoint):
            raise TypeError("System Error: Can only add two SafePoint objects.")
        return SafePoint(self.x + other.x, self.y + other.y)

try:
    SafePoint(5, 5) + 100
except TypeError as error:
    print(error)

System Error: Can only add two SafePoint objects.


### ***Edge-Case Test:***
If you want to compare if two coordinates are exactly identical (e.g., `p1 == p2`), Python will return `False` even if the coordinates are both `(5,5)`. Why? Because they live in different memory locations. You must overload the equals operator `def __eq__(self, other):` to teach Python to compare their `.x` and `.y` values instead of their memory slots.

![alt text](gemini-svg_95.svg)